package edu.wpi.first.wpilibj.communication;

import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.ShortBuffer;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import edu.wpi.first.wpilibj.hal.JNIWrapper;

/**
 * JNA Wrapper for library <b>FRC_NetworkCommunications</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@objid ("1667a304-f5b4-46de-9440-8cae16a6df7d")
public class FRCNetworkCommunicationsLibrary extends JNIWrapper {
    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("733dabcb-8cb2-4793-bcd4-30bee3e83fe1")
    public static final int kFRC_NetworkCommunication_DynamicType_DSEnhancedIO_Input = 17;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("e1eec1d3-d1b9-4a63-bbac-5f7ed3c3d03c")
    public static final int kFRC_NetworkCommunication_DynamicType_Kinect_Vertices1 = 21;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("db12e8c5-75b5-4c5a-9a8e-1369184832f3")
    public static final int SYS_STATUS_DATA_SIZE = 44;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("b488c04f-1603-4ed1-b164-f007a086469e")
    public static final int kFRC_NetworkCommunication_DynamicType_Kinect_Custom = 25;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("31ebc124-fd56-41eb-965e-ade34ac10b74")
    public static final int kFRC_NetworkCommunication_DynamicType_Kinect_Vertices2 = 23;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("547e4c7d-dc2e-4a89-bbc9-471018ff3590")
    public static final int kFRC_NetworkCommunication_DynamicType_Kinect_Header = 19;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("d87d8fb8-e0ea-4000-8a2c-39d6443dfad6")
    public static final int kFRC_NetworkCommunication_DynamicType_Kinect_Joystick = 24;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("5634d7ec-57c5-4a62-87c5-dd7cc5708f58")
    public static final int IO_CONFIG_DATA_SIZE = 32;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h</i>
     */
    @objid ("378c6521-0530-4068-96b2-bf2a8c35a7ae")
    public static final int kMaxModuleNumber = 2;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("3f871c9b-c459-4a18-919e-7cd302edaac9")
    public static final int kFRC_NetworkCommunication_DynamicType_DSEnhancedIO_Output = 18;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("2f5af25f-4436-49ba-b57e-6183a0cad92a")
    public static final int kFRC_NetworkCommunication_DynamicType_Kinect_Extra2 = 22;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("3151d62f-1bcb-444b-b836-59db07c9c54b")
    public static final int kFRC_NetworkCommunication_DynamicType_Kinect_Extra1 = 20;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("d909143d-96ff-4ea4-955c-93329f358f3f")
    public static final int USER_DS_LCD_DATA_SIZE = 128;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h</i>
     */
    @objid ("ef398028-b137-4ea8-95c6-f0008d395f66")
    public static final int kUsageReporting_version = 1;

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h</i>
     */
    @objid ("e6a785b6-8732-402c-8c04-3f8180c4cd2a")
    public static final int USER_STATUS_DATA_SIZE = (984 - 32 - 44);

    @objid ("689ca486-a3fc-40dd-8dd4-3dcf351b2fce")
    public static int kMaxJoystickAxes = 12;

    @objid ("e3563fc6-c915-4e67-8265-b878cc612d6e")
    public static int kMaxJoystickPOVs = 12;

//@Deprecated
//public static native int FRC_NetworkCommunication_nAICalibration_getLSBWeight(int aiSystemIndex, int channel, Integer status);
    /**
     * Original signature : <code>uint32_t FRC_NetworkCommunication_nAICalibration_getLSBWeight(const uint32_t, const uint32_t, int32_t*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\AICalibration.h:7</i><br>
     * @deprecated use the safer methods {@link #FRC_NetworkCommunication_nAICalibration_getLSBWeight(int, int, java.nio.IntBuffer)} and {@link #FRC_NetworkCommunication_nAICalibration_getLSBWeight(int, int, com.sun.jna.ptr.IntByReference)} instead
     * Original signature : <code>uint32_t FRC_NetworkCommunication_nAICalibration_getLSBWeight(const uint32_t, const uint32_t, int32_t*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\AICalibration.h:7</i>
     */
    @objid ("a479db79-3cd9-4005-aeea-d163823ed55a")
    public static native int FRCNetworkCommunicationAICalibrationGetLSBWeight(int aiSystemIndex, int channel, Integer status);

//@Deprecated
//public static native int FRC_NetworkCommunication_nAICalibration_getOffset(int aiSystemIndex, int channel, Integer status);
    /**
     * Original signature : <code>int32_t FRC_NetworkCommunication_nAICalibration_getOffset(const uint32_t, const uint32_t, int32_t*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\AICalibration.h:8</i><br>
     * @deprecated use the safer methods {@link #FRC_NetworkCommunication_nAICalibration_getOffset(int, int, java.nio.IntBuffer)} and {@link #FRC_NetworkCommunication_nAICalibration_getOffset(int, int, com.sun.jna.ptr.IntByReference)} instead
     * Original signature : <code>int32_t FRC_NetworkCommunication_nAICalibration_getOffset(const uint32_t, const uint32_t, int32_t*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\AICalibration.h:8</i>
     */
    @objid ("147c1fb9-320a-4f0a-8c66-308d63fc05cc")
    public static native int FRCNetworkCommunicationAICalibrationGetOffset(int aiSystemIndex, int channel, Integer status);

    /**
     * Original signature : <code>tTargetClass getTargetClass()</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:25</i>
     */
    @objid ("7d9b38f6-90e5-41ed-8f24-37b86ce409fd")
    public static native int getTargetClass();

    /**
     * Original signature : <code>uint32_t FRC_NetworkCommunication_nLoadOut_getModulePresence(uint32_t, uint8_t)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:32</i>
     */
    @objid ("9d0a5467-cec7-4937-bb98-7636b64aad17")
    public static native int FRCNetworkCommunicationLoadOutGetModulePresence(int moduleType, byte moduleNumber);

    /**
     * Original signature : <code>uint32_t FRC_NetworkCommunication_nLoadOut_getTargetClass()</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:33</i>
     */
    @objid ("1f44c943-f0c9-4911-977a-889ec7244a3c")
    public static native int FRCNetworkCommunicationLoadOutGetTargetClass();

//@Deprecated
//public static native FRC_NetworkCommunicationsLibrary.STATUS moduleNameFindBySymbolName(Pointer symbol, Pointer module);
//public static native FRC_NetworkCommunicationsLibrary.STATUS moduleNameFindBySymbolName(String symbol, ByteBuffer module);
//@Deprecated
//public static native int report(int resource, byte instanceNumber, byte context, Pointer feature);
    /**
     * Original signature : <code>STATUS moduleNameFindBySymbolName(const char*, char*)</code><br>
     * @param symbol symbol name to look for<br>
     * @param module where to return module name<br>
     * <i>native declaration : src\main\include\NetworkCommunication\symModuleLink.h:6</i><br>
     * @deprecated use the safer methods {@link #moduleNameFindBySymbolName(java.lang.String, java.nio.ByteBuffer)} and {@link #moduleNameFindBySymbolName(com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
     * Original signature : <code>STATUS moduleNameFindBySymbolName(const char*, char*)</code><br>
     * @param symbol symbol name to look for<br>
     * @param module where to return module name<br>
     * <i>native declaration : src\main\include\NetworkCommunication\symModuleLink.h:6</i>
     * Report the usage of a resource of interest.
     * <br>
     * 
     * <br>
     * @param resource one of the values in the tResourceType above (max value 51).
     * <br>
     * @param instanceNumber an index that identifies the resource instance.
     * <br>
     * @param context an optional additional context number for some cases (such as module number).  Set to 0 to omit.
     * <br>
     * @param feature a string to be included describing features in use on a specific resource.  Setting the same resource more than once allows you to change the feature string.<br>
     * Original signature : <code>uint32_t report(tResourceType, uint8_t, uint8_t, const char*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:113</i>
     */
    @objid ("3d1678c2-3b49-4de2-89bf-eb97c84795e2")
    public static native int report(int resource, byte instanceNumber, byte context, String feature);

//@Deprecated
//public static native int FRC_NetworkCommunication_nUsageReporting_report(byte resource, byte instanceNumber, byte context, Pointer feature);
    /**
     * Original signature : <code>uint32_t FRC_NetworkCommunication_nUsageReporting_report(uint8_t, uint8_t, uint8_t, const char*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:120</i><br>
     * @deprecated use the safer methods {@link #FRC_NetworkCommunication_nUsageReporting_report(byte, byte, byte, java.lang.String)} and {@link #FRC_NetworkCommunication_nUsageReporting_report(byte, byte, byte, com.sun.jna.Pointer)} instead
     * Original signature : <code>uint32_t FRC_NetworkCommunication_nUsageReporting_report(uint8_t, uint8_t, uint8_t, const char*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:120</i>
     */
    @objid ("2b750a8f-464c-4aa3-9756-93f9a1544c41")
    public static native int FRCNetworkCommunicationUsageReportingReport(byte resource, byte instanceNumber, byte context, String feature);

//@Deprecated
//public static native void getFPGAHardwareVersion(ShortByReference fpgaVersion, IntByReference fpgaRevision);
    /**
     * Original signature : <code>void getFPGAHardwareVersion(uint16_t*, uint32_t*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:124</i><br>
     * @deprecated use the safer methods {@link #getFPGAHardwareVersion(java.nio.ShortBuffer, java.nio.IntBuffer)} and {@link #getFPGAHardwareVersion(com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.IntByReference)} instead
     * Original signature : <code>void getFPGAHardwareVersion(uint16_t*, uint32_t*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:124</i>
     */
    @objid ("4c105e88-ac1a-4be0-bc50-6da0688bc313")
    public static native void getFPGAHardwareVersion(ShortBuffer fpgaVersion, IntBuffer fpgaRevision);

//@Deprecated
//public static native int setErrorData(Pointer errors, int errorsLength, int wait_ms);
    /**
     * Original signature : <code>int setErrorData(const char*, int, int)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:136</i><br>
     * @deprecated use the safer methods {@link #setErrorData(java.lang.String, int, int)} and {@link #setErrorData(com.sun.jna.Pointer, int, int)} instead
     * Original signature : <code>int setErrorData(const char*, int, int)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:136</i>
     */
    @objid ("d85bd86c-3191-4212-ab05-8a25b087c4dc")
    public static native int setErrorData(String errors, int errorsLength, int wait_ms);

//@Deprecated
//public static native int overrideIOConfig(String ioConfig, int wait_ms);
    /**
     * Original signature : <code>int overrideIOConfig(const char*, int)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:138</i><br>
     * @deprecated use the safer methods {@link #overrideIOConfig(java.lang.String, int)} and {@link #overrideIOConfig(com.sun.jna.Pointer, int)} instead
     * Original signature : <code>int overrideIOConfig(const char*, int)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:138</i>
     */
    @objid ("5e411142-3e28-4d1a-9b4d-6b5b3a5ab86c")
    public static native int overrideIOConfig(String ioConfig, int wait_ms);

    /**
     * Original signature : <code>void setNewDataSem(pthread_mutex_t*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:147</i>
     */
    @objid ("cfbe1523-d40c-48c1-85af-ace3f5ef621f")
    public static native void setNewDataSem(ByteBuffer mutexId);

//public static native void setResyncSem(FRC_NetworkCommunicationsLibrary.pthread_mutex_t pthread_mutex_tPtr1);
    /**
     * Original signature : <code>void setResyncSem(pthread_mutex_t*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:148</i>
     * Original signature : <code>void signalResyncActionDone()</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:150</i>
     */
    @objid ("f072ad36-4010-482d-8f60-408b6b6e6d7a")
    public static native void signalResyncActionDone();

    /**
     * this uint32_t is really a LVRefNum<br>
     * Original signature : <code>void setNewDataOccurRef(uint32_t)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:154</i>
     */
    @objid ("90002ba7-2a3c-4135-9892-4c04e8420cad")
    public static native void setNewDataOccurRef(int refnum);

    /**
     * Original signature : <code>void setResyncOccurRef(uint32_t)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:156</i>
     */
    @objid ("21af53fd-7078-423d-9518-3cb266f53ffe")
    public static native void setResyncOccurRef(int refnum);

//@Deprecated
//public static native void FRC_NetworkCommunication_getVersionString(Pointer version);
    /**
     * Original signature : <code>void FRC_NetworkCommunication_getVersionString(char*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:159</i><br>
     * @deprecated use the safer methods {@link #FRC_NetworkCommunication_getVersionString(java.nio.ByteBuffer)} and {@link #FRC_NetworkCommunication_getVersionString(com.sun.jna.Pointer)} instead
     * Original signature : <code>void FRC_NetworkCommunication_getVersionString(char*)</code><br>
     * <i>native declaration : src\main\include\NetworkCommunication\FRCComm.h:159</i>
     */
    @objid ("d9e2f08d-aee2-4ba5-a83b-4dc3fb030a1f")
    public static native void FRCNetworkCommunicationGetVersionString(ByteBuffer version);

    @objid ("50bf4e02-24b9-4945-b223-7eaa9ea3e8d4")
    public static native void FRCNetworkCommunicationObserveUserProgramStarting();

    @objid ("80372488-0613-469d-a4e6-5f986853c68f")
    public static native void FRCNetworkCommunicationObserveUserProgramDisabled();

    @objid ("223d9641-3a01-4535-80ae-dca7d26d5213")
    public static native void FRCNetworkCommunicationObserveUserProgramAutonomous();

    @objid ("a37b22bf-89e5-4a22-bf58-7035fb2dd991")
    public static native void FRCNetworkCommunicationObserveUserProgramTeleop();

    @objid ("bef4f5c5-5576-4b6e-94d4-cbb865c1aaa1")
    public static native void FRCNetworkCommunicationObserveUserProgramTest();

    @objid ("cd1e784f-52e7-43e0-b2d4-bd7ab92e45c3")
    public static native void FRCNetworkCommunicationReserve();

    @objid ("51bd98a3-4edf-412c-bbb2-c050eb28119d")
    private static native int NativeHALGetControlWord();

    @objid ("7b629a4b-b16e-4ae4-a0ca-319892922180")
    public static HALControlWord HALGetControlWord() {
        int word = NativeHALGetControlWord();
        return new HALControlWord(
                    (word & 1) != 0,
                    ((word >> 1) & 1) != 0,
                    ((word >> 2) & 1) != 0,
                    ((word >> 3) & 1) != 0,
                    ((word >> 4) & 1) != 0,
                    ((word >> 5) & 1) != 0
                );
    }

    @objid ("02c228ac-58a6-4a28-acf6-9b7bda6b2e6b")
    private static native int NativeHALGetAllianceStation();

    @objid ("1f298d94-c815-4e4f-81a4-ddd5d4b43813")
    public static HALAllianceStationID HALGetAllianceStation() {
        switch(NativeHALGetAllianceStation()) {
        case 0:
            return HALAllianceStationID.Red1;
        case 1:
            return HALAllianceStationID.Red2;
        case 2:
            return HALAllianceStationID.Red3;
        case 3:
            return HALAllianceStationID.Blue1;
        case 4:
            return HALAllianceStationID.Blue2;
        case 5:
            return HALAllianceStationID.Blue3;
        default:
            return null;
        }
    }

    @objid ("95df9325-ac3c-4998-b696-1672de82974e")
    public static native short[] HALGetJoystickAxes(byte joystickNum);

    @objid ("afe3e5e1-1a4f-452d-8d2d-1bc4194ab2d1")
    public static native short[] HALGetJoystickPOVs(byte joystickNum);

    @objid ("c0ff23c9-aa44-467a-88c8-8c7b6bee1a35")
    public static native int HALGetJoystickButtons(byte joystickNum, ByteBuffer count);

    @objid ("83d4b0cb-8f41-4228-b3d5-296e9be4a629")
    public static native int HALSetJoystickOutputs(byte joystickNum, int outputs, short leftRumble, short rightRumble);

    @objid ("d839299e-836f-47bf-9680-796bcea12090")
    public static native float HALGetMatchTime();

    @objid ("195d118a-3510-49b4-acf8-3133504abb8e")
    public static native boolean HALGetSystemActive(IntBuffer status);

    @objid ("05c47000-c6e8-4318-8ac7-921ea5388cb5")
    public static native boolean HALGetBrownedOut(IntBuffer status);

    @objid ("56bde858-07ce-449b-82d8-c4fc13c5d8b5")
    public static native int HALSetErrorData(String error);

//public static final String JNA_LIBRARY_NAME = LibraryExtractor.getLibraryPath("FRC_NetworkCommunications", true, FRC_NetworkCommunicationsLibrary.class);
//public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(FRC_NetworkCommunicationsLibrary.JNA_LIBRARY_NAME, MangledFunctionMapper.DEFAULT_OPTIONS);
//static {
//System.loadLibrary("JNIWrappers");
//Native.register(FRC_NetworkCommunicationsLibrary.class, FRC_NetworkCommunicationsLibrary.JNA_NATIVE_LIB);
//}
    /**
     * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h</i><br>
     * enum values
     */
    @objid ("d8a3c103-74d3-4763-bd55-354593a36ba0")
    public interface tModuleType {
        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:9</i>
         */
        @objid ("1215c20b-0282-464e-91dd-dff512ec46b0")
        public static final int kModuleType_Unknown = 0x00;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:10</i>
         */
        @objid ("b73e722e-1829-41fe-9a0f-4e2a85b23a9e")
        public static final int kModuleType_Analog = 0x01;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:11</i>
         */
        @objid ("67b3ef76-7069-4e31-ba64-0eccc2940226")
        public static final int kModuleType_Digital = 0x02;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:12</i>
         */
        @objid ("59e1bcdb-c66d-440c-ac7e-20af3f30e5c3")
        public static final int kModuleType_Solenoid = 0x03;

    }

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h</i><br>
     * enum values
     */
    @objid ("43e5c7e5-df3d-4887-a0e0-d64ef0e1bf13")
    public interface tTargetClass {
        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:16</i>
         */
        @objid ("e5fa30e4-daea-4ad8-a674-daf3745ea51f")
        public static final int kTargetClass_Unknown = 0x00;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:17</i>
         */
        @objid ("7f290a55-f225-4f5e-9880-5204ccf2bad6")
        public static final int kTargetClass_FRC1 = 0x10;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:18</i>
         */
        @objid ("1d802bd8-5374-4290-be3e-650393b6c7cb")
        public static final int kTargetClass_FRC2 = 0x20;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:19</i>
         */
        @objid ("10fffd36-b772-4f14-8b00-6752397013bb")
        public static final int kTargetClass_FRC2_Analog = (int)FRCNetworkCommunicationsLibrary.tTargetClass.kTargetClass_FRC2 | (int)FRCNetworkCommunicationsLibrary.tModuleType.kModuleType_Analog;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:20</i>
         */
        @objid ("c153ce9d-e85f-4fb2-a2f2-ec0b248f878d")
        public static final int kTargetClass_FRC2_Digital = (int)FRCNetworkCommunicationsLibrary.tTargetClass.kTargetClass_FRC2 | (int)FRCNetworkCommunicationsLibrary.tModuleType.kModuleType_Digital;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:21</i>
         */
        @objid ("5a8a3a49-6708-4478-aa75-d43eb315e8c7")
        public static final int kTargetClass_FRC2_Solenoid = (int)FRCNetworkCommunicationsLibrary.tTargetClass.kTargetClass_FRC2 | (int)FRCNetworkCommunicationsLibrary.tModuleType.kModuleType_Solenoid;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:22</i>
         */
        @objid ("cbacadd7-d556-4d6b-a289-539a8e8345d9")
        public static final int kTargetClass_FamilyMask = 0xF0;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\LoadOut.h:23</i>
         */
        @objid ("c02ef2e1-026f-4962-ae66-e8a2ec3d169d")
        public static final int kTargetClass_ModuleMask = 0x0F;

    }

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h</i><br>
     * enum values
     */
    @objid ("d1d89951-ca07-4d99-91da-813b28b32749")
    public interface tResourceType {
        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:10</i>
         */
        @objid ("36799ef9-91f7-42bf-b122-16cbe22bb218")
        public static final int kResourceType_Controller = 0;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:11</i>
         */
        @objid ("14d26420-8635-4e22-b3d4-594297ca4d0f")
        public static final int kResourceType_Module = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:12</i>
         */
        @objid ("9dc87016-0c86-42a4-bb2c-5458acd4ec62")
        public static final int kResourceType_Language = 2;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:13</i>
         */
        @objid ("fd53bd0c-c5bd-4e1e-94eb-250141aa53e4")
        public static final int kResourceType_CANPlugin = 3;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:14</i>
         */
        @objid ("cc865e7b-8aa1-4a82-9161-e27715cc6a6b")
        public static final int kResourceType_Accelerometer = 4;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:15</i>
         */
        @objid ("1b02ef8e-15e5-4a31-a81a-df5bdc3d632b")
        public static final int kResourceType_ADXL345 = 5;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:16</i>
         */
        @objid ("04cfb9c1-5bca-40d4-af2f-71d4321e5cc6")
        public static final int kResourceType_AnalogChannel = 6;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:17</i>
         */
        @objid ("55124b46-973f-44e3-a1f1-a4dba2b0670c")
        public static final int kResourceType_AnalogTrigger = 7;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:18</i>
         */
        @objid ("5dbff220-bac8-439c-9dae-2aaa69dacff1")
        public static final int kResourceType_AnalogTriggerOutput = 8;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:19</i>
         */
        @objid ("f56b8b92-3b91-44b3-b90e-3913837769ef")
        public static final int kResourceType_CANJaguar = 9;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:20</i>
         */
        @objid ("5b106bf1-d947-478f-8a97-f811095b6405")
        public static final int kResourceType_Compressor = 10;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:21</i>
         */
        @objid ("abf3cb83-420c-4af2-914a-737b39062bd3")
        public static final int kResourceType_Counter = 11;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:22</i>
         */
        @objid ("69c3a22d-1979-4f3e-9f86-c0112d7491a5")
        public static final int kResourceType_Dashboard = 12;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:23</i>
         */
        @objid ("526c005c-6474-4cf9-b35a-eae6eacbd3d4")
        public static final int kResourceType_DigitalInput = 13;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:24</i>
         */
        @objid ("174d9303-5e40-4fac-a68e-f6ea8fe5d96e")
        public static final int kResourceType_DigitalOutput = 14;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:25</i>
         */
        @objid ("b4ee2d69-a25c-4dc7-a3b5-9f621f6b04cb")
        public static final int kResourceType_DriverStationCIO = 15;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:26</i>
         */
        @objid ("412236cd-dd96-467f-87db-bf8d9fd2d12b")
        public static final int kResourceType_DriverStationEIO = 16;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:27</i>
         */
        @objid ("573db59e-0837-4302-936e-12198c413f6f")
        public static final int kResourceType_DriverStationLCD = 17;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:28</i>
         */
        @objid ("c792c080-daf0-407f-b164-6157dabe6f51")
        public static final int kResourceType_Encoder = 18;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:29</i>
         */
        @objid ("ffb4a76c-ab81-40cb-a7cd-dd50289df9bb")
        public static final int kResourceType_GearTooth = 19;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:30</i>
         */
        @objid ("28f16be1-c25f-416d-908e-49ec72905be2")
        public static final int kResourceType_Gyro = 20;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:31</i>
         */
        @objid ("8b5b0b24-b938-42fc-9802-1b4ebba7163a")
        public static final int kResourceType_I2C = 21;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:32</i>
         */
        @objid ("337ee222-a75e-4539-ac17-fa4aee36f26a")
        public static final int kResourceType_Framework = 22;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:33</i>
         */
        @objid ("22893afd-e63c-4f4f-b1b5-6bdd81807411")
        public static final int kResourceType_Jaguar = 23;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:34</i>
         */
        @objid ("648c7449-4872-4fba-9ef5-dec3a24fffdf")
        public static final int kResourceType_Joystick = 24;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:35</i>
         */
        @objid ("edca3ec7-90ec-4ec9-aea8-8bf660b09432")
        public static final int kResourceType_Kinect = 25;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:36</i>
         */
        @objid ("0ef295dc-7de7-4ab3-a125-37fc8caf118b")
        public static final int kResourceType_KinectStick = 26;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:37</i>
         */
        @objid ("a103b9bf-acf9-4df2-9ec1-ea6dc3bec64f")
        public static final int kResourceType_PIDController = 27;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:38</i>
         */
        @objid ("5adfb6a7-027a-492f-8962-49e0b686a1e5")
        public static final int kResourceType_Preferences = 28;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:39</i>
         */
        @objid ("f933c2cb-3206-4711-aebb-061c08cd0a3b")
        public static final int kResourceType_PWM = 29;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:40</i>
         */
        @objid ("8d24bd39-8ba4-43d2-ba9a-bb534ae26bd5")
        public static final int kResourceType_Relay = 30;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:41</i>
         */
        @objid ("56e0949f-1524-4485-85a0-09626a05ab04")
        public static final int kResourceType_RobotDrive = 31;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:42</i>
         */
        @objid ("0c25c9c2-2e2e-44dc-a8df-a35206238ade")
        public static final int kResourceType_SerialPort = 32;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:43</i>
         */
        @objid ("160145fd-1407-4d1a-b665-c6c013bbc886")
        public static final int kResourceType_Servo = 33;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:44</i>
         */
        @objid ("2e8a05bf-f68e-4bce-92f3-e5c2e367a26f")
        public static final int kResourceType_Solenoid = 34;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:45</i>
         */
        @objid ("e324cf23-a14f-4b54-9318-86bd2cf7d4ed")
        public static final int kResourceType_SPI = 35;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:46</i>
         */
        @objid ("c9c54e1c-7e6f-423f-a880-ec06361bad43")
        public static final int kResourceType_Task = 36;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:47</i>
         */
        @objid ("588ccb4e-63d9-4582-ba51-0ff361554b96")
        public static final int kResourceType_Ultrasonic = 37;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:48</i>
         */
        @objid ("0262da78-037d-4cd9-af76-600fcf95c812")
        public static final int kResourceType_Victor = 38;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:49</i>
         */
        @objid ("79635c99-ed82-43e3-bdd5-eefe15f38233")
        public static final int kResourceType_Button = 39;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:50</i>
         */
        @objid ("42264a26-c00d-46aa-938c-c9b71bee6116")
        public static final int kResourceType_Command = 40;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:51</i>
         */
        @objid ("0e2fdc5b-0844-4b79-8ea5-6cb1b71f3692")
        public static final int kResourceType_AxisCamera = 41;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:52</i>
         */
        @objid ("0beb47fc-eb2f-4547-91bd-29b3a3b49875")
        public static final int kResourceType_PCVideoServer = 42;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:53</i>
         */
        @objid ("8cb3bcee-6a02-43b5-bdc0-aa6bd2d88253")
        public static final int kResourceType_SmartDashboard = 43;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:54</i>
         */
        @objid ("fc6fd882-3444-4c8a-8082-8ff4c7c1e8c4")
        public static final int kResourceType_Talon = 44;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:55</i>
         */
        @objid ("a77beb04-7168-4c38-9ff7-15d1072aaf32")
        public static final int kResourceType_HiTechnicColorSensor = 45;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:56</i>
         */
        @objid ("ee75d86c-0dc4-4dc1-a033-8c3650f578fb")
        public static final int kResourceType_HiTechnicAccel = 46;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:57</i>
         */
        @objid ("ed644d34-8fe1-4b38-a10b-481d4c6aa85f")
        public static final int kResourceType_HiTechnicCompass = 47;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:58</i>
         */
        @objid ("adf92936-604d-403d-ad97-0ca4d0c084b4")
        public static final int kResourceType_SRF08 = 48;

    }

    /**
     * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h</i><br>
     * enum values
     */
    @objid ("213f2902-a23e-423a-8bdc-924688aca483")
    public interface tInstances {
        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:63</i>
         */
        @objid ("90a2658d-6967-4dfa-bd43-e3367ef3c239")
        public static final int kLanguage_LabVIEW = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:64</i>
         */
        @objid ("db175c37-01df-4b5c-b109-9efbf7eaaed8")
        public static final int kLanguage_CPlusPlus = 2;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:65</i>
         */
        @objid ("2791879d-ba28-4069-be9e-4093288fe407")
        public static final int kLanguage_Java = 3;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:66</i>
         */
        @objid ("86a49b99-7d37-43de-90f1-1c637d2dfa14")
        public static final int kLanguage_Python = 4;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:68</i>
         */
        @objid ("bcba3a8c-356b-4cb9-ad96-32e93ac7644c")
        public static final int kCANPlugin_BlackJagBridge = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:69</i>
         */
        @objid ("8db73d3f-1302-478a-b7de-8c23727daab2")
        public static final int kCANPlugin_2CAN = 2;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:71</i>
         */
        @objid ("ec2865ff-99cd-413a-ab94-886e37b17110")
        public static final int kFramework_Iterative = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:72</i>
         */
        @objid ("543aa189-28f1-414b-8233-c19f979ed684")
        public static final int kFramework_Simple = 2;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:74</i>
         */
        @objid ("7628f8a4-27d1-4500-8705-050b04137ee4")
        public static final int kRobotDrive_ArcadeStandard = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:75</i>
         */
        @objid ("84f48465-dd4f-40ff-aa41-4092e7850f1e")
        public static final int kRobotDrive_ArcadeButtonSpin = 2;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:76</i>
         */
        @objid ("1df115fc-b709-490c-a431-64169244df44")
        public static final int kRobotDrive_ArcadeRatioCurve = 3;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:77</i>
         */
        @objid ("3d52915c-a4d3-473d-a7e2-eb31cee31c44")
        public static final int kRobotDrive_Tank = 4;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:78</i>
         */
        @objid ("bdc06a6e-d609-43f4-acfe-94ce286c1363")
        public static final int kRobotDrive_MecanumPolar = 5;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:79</i>
         */
        @objid ("b31a0095-8586-4cb2-a15f-73e834aa8daa")
        public static final int kRobotDrive_MecanumCartesian = 6;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:81</i>
         */
        @objid ("1671773d-4d7c-4c77-9836-0f19eba9b31f")
        public static final int kDriverStationCIO_Analog = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:82</i>
         */
        @objid ("e8b611da-0702-4ec4-8fff-97bd08ec9a00")
        public static final int kDriverStationCIO_DigitalIn = 2;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:83</i>
         */
        @objid ("ceaad2c6-b2f6-4b53-ba10-a60f615c23d5")
        public static final int kDriverStationCIO_DigitalOut = 3;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:85</i>
         */
        @objid ("dfcadcc3-7f02-44b6-91db-62044d42ac85")
        public static final int kDriverStationEIO_Acceleration = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:86</i>
         */
        @objid ("f95819e4-e93e-49fe-bd12-0dfb8ad61066")
        public static final int kDriverStationEIO_AnalogIn = 2;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:87</i>
         */
        @objid ("267126cb-d2a3-4f71-bb7a-1170d5271081")
        public static final int kDriverStationEIO_AnalogOut = 3;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:88</i>
         */
        @objid ("79b41956-b7ce-4f84-b73b-49cef587d005")
        public static final int kDriverStationEIO_Button = 4;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:89</i>
         */
        @objid ("8d9c8b5c-059c-43b3-bb7c-89bba4bacee9")
        public static final int kDriverStationEIO_LED = 5;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:90</i>
         */
        @objid ("5349b4df-da2e-4295-8afb-1683e169ffed")
        public static final int kDriverStationEIO_DigitalIn = 6;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:91</i>
         */
        @objid ("932a11f2-cde0-47ee-8aef-c614b16a4646")
        public static final int kDriverStationEIO_DigitalOut = 7;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:92</i>
         */
        @objid ("773c8fe9-ac77-4db7-8263-34cffe3d13b3")
        public static final int kDriverStationEIO_FixedDigitalOut = 8;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:93</i>
         */
        @objid ("78fc6da4-8e6c-4780-a120-30c5fc2a0202")
        public static final int kDriverStationEIO_PWM = 9;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:94</i>
         */
        @objid ("e2e0a7fb-1a86-4308-810c-52d3e2e2dda7")
        public static final int kDriverStationEIO_Encoder = 10;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:95</i>
         */
        @objid ("05b8df8f-d579-4118-b1f9-a2112515bb3f")
        public static final int kDriverStationEIO_TouchSlider = 11;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:97</i>
         */
        @objid ("d08d7ded-b445-4410-b924-f174136d1dc0")
        public static final int kADXL345_SPI = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:98</i>
         */
        @objid ("782a4c5b-9664-4659-a433-b2df0a8fc840")
        public static final int kADXL345_I2C = 2;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:100</i>
         */
        @objid ("bf3b6470-abca-441d-88ad-c467248146a8")
        public static final int kCommand_Scheduler = 1;

        /**
         * <i>native declaration : src\main\include\NetworkCommunication\UsageReporting.h:102</i>
         */
        @objid ("f78b93f2-1618-4f63-8816-26601da5c620")
        public static final int kSmartDashboard_Instance = 1;

    }

}
