/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("ade78aeb-d3fd-40c5-a8e3-389e87d78dd6")
public class CanTalonSRX extends CtreCanNode {
    @objid ("a15a0433-fc72-4c35-97ce-95106c42f503")
    private long swigCPtr;

    @objid ("92eaba7e-1314-4d8d-b046-4278cdc9c7b1")
    public static final int kDefaultControlPeriodMs = CanTalonJNI.CanTalonSRX_kDefaultControlPeriodMs_get();

    @objid ("1e37eb5d-273a-49ea-9195-6ae10cee8fa3")
    public static final int kMode_DutyCycle = CanTalonJNI.CanTalonSRX_kMode_DutyCycle_get();

    @objid ("2189c456-04ce-4674-afda-b3ad468abd84")
    public static final int kMode_PositionCloseLoop = CanTalonJNI.CanTalonSRX_kMode_PositionCloseLoop_get();

    @objid ("d4a69eac-a17b-4d0d-ac81-b83a7aea170d")
    public static final int kMode_VelocityCloseLoop = CanTalonJNI.CanTalonSRX_kMode_VelocityCloseLoop_get();

    @objid ("0a3d0e44-e590-4dec-86b3-5b73f6f297da")
    public static final int kMode_CurrentCloseLoop = CanTalonJNI.CanTalonSRX_kMode_CurrentCloseLoop_get();

    @objid ("b9742aea-872c-43d8-a55c-8d097eeb082d")
    public static final int kMode_VoltCompen = CanTalonJNI.CanTalonSRX_kMode_VoltCompen_get();

    @objid ("8093e21d-3869-4da2-85c3-199fcf4ce9fe")
    public static final int kMode_SlaveFollower = CanTalonJNI.CanTalonSRX_kMode_SlaveFollower_get();

    @objid ("71dec466-7f1b-47a4-b619-4ede53d119b1")
    public static final int kMode_NoDrive = CanTalonJNI.CanTalonSRX_kMode_NoDrive_get();

    @objid ("1eb46a23-07b9-4c1e-8c02-2b7ec7f171f8")
    public static final int kLimitSwitchOverride_UseDefaultsFromFlash = CanTalonJNI.CanTalonSRX_kLimitSwitchOverride_UseDefaultsFromFlash_get();

    @objid ("b2029d93-9f7a-4c40-a118-b520b815c146")
    public static final int kLimitSwitchOverride_DisableFwd_DisableRev = CanTalonJNI.CanTalonSRX_kLimitSwitchOverride_DisableFwd_DisableRev_get();

    @objid ("8bcab56e-15ce-44cb-ae46-2edfdf421558")
    public static final int kLimitSwitchOverride_DisableFwd_EnableRev = CanTalonJNI.CanTalonSRX_kLimitSwitchOverride_DisableFwd_EnableRev_get();

    @objid ("1fe4399d-fc42-45a4-8e6b-c3ff54e31aea")
    public static final int kLimitSwitchOverride_EnableFwd_DisableRev = CanTalonJNI.CanTalonSRX_kLimitSwitchOverride_EnableFwd_DisableRev_get();

    @objid ("5bb2dea1-52e9-425f-b1f3-93b83a29bba2")
    public static final int kLimitSwitchOverride_EnableFwd_EnableRev = CanTalonJNI.CanTalonSRX_kLimitSwitchOverride_EnableFwd_EnableRev_get();

    @objid ("f8b352b6-66b2-41b0-834c-708d2d38c8bd")
    public static final int kBrakeOverride_UseDefaultsFromFlash = CanTalonJNI.CanTalonSRX_kBrakeOverride_UseDefaultsFromFlash_get();

    @objid ("9bf40f73-8421-4627-84dd-73eaa6b48e64")
    public static final int kBrakeOverride_OverrideCoast = CanTalonJNI.CanTalonSRX_kBrakeOverride_OverrideCoast_get();

    @objid ("31f32b3a-98fc-4467-8393-9b451b7413f8")
    public static final int kBrakeOverride_OverrideBrake = CanTalonJNI.CanTalonSRX_kBrakeOverride_OverrideBrake_get();

    @objid ("2c2e7a2c-e5ea-4824-93ee-44dbb4ddd7ba")
    public static final int kFeedbackDev_DigitalQuadEnc = CanTalonJNI.CanTalonSRX_kFeedbackDev_DigitalQuadEnc_get();

    @objid ("acae7455-11e4-4dea-b05a-71fdd4680659")
    public static final int kFeedbackDev_AnalogPot = CanTalonJNI.CanTalonSRX_kFeedbackDev_AnalogPot_get();

    @objid ("62b44932-b3a5-4add-afa0-9eaa604905c2")
    public static final int kFeedbackDev_AnalogEncoder = CanTalonJNI.CanTalonSRX_kFeedbackDev_AnalogEncoder_get();

    @objid ("cda7b434-c6ef-4329-b95f-afcbb3905fef")
    public static final int kFeedbackDev_CountEveryRisingEdge = CanTalonJNI.CanTalonSRX_kFeedbackDev_CountEveryRisingEdge_get();

    @objid ("cd042f91-77e1-455f-8980-af70c8937547")
    public static final int kFeedbackDev_CountEveryFallingEdge = CanTalonJNI.CanTalonSRX_kFeedbackDev_CountEveryFallingEdge_get();

    @objid ("2ef12113-c5f3-4ccd-8dda-d5af28ef7e75")
    public static final int kFeedbackDev_PosIsPulseWidth = CanTalonJNI.CanTalonSRX_kFeedbackDev_PosIsPulseWidth_get();

    @objid ("6299c30e-d485-4737-a44f-9b6fcd30e406")
    public static final int kProfileSlotSelect_Slot0 = CanTalonJNI.CanTalonSRX_kProfileSlotSelect_Slot0_get();

    @objid ("ec62dc68-235c-4643-a95c-b72b4f40dfc9")
    public static final int kProfileSlotSelect_Slot1 = CanTalonJNI.CanTalonSRX_kProfileSlotSelect_Slot1_get();

    @objid ("8e62ff62-9789-4154-a8f4-32c493f43084")
    public static final int kStatusFrame_General = CanTalonJNI.CanTalonSRX_kStatusFrame_General_get();

    @objid ("e0cbf160-adee-4b9c-bfe0-07c6c65f4fa2")
    public static final int kStatusFrame_Feedback = CanTalonJNI.CanTalonSRX_kStatusFrame_Feedback_get();

    @objid ("9db2f392-cc18-4d12-80b5-46f009a1623e")
    public static final int kStatusFrame_Encoder = CanTalonJNI.CanTalonSRX_kStatusFrame_Encoder_get();

    @objid ("6c74f51f-154b-4511-8884-8b51a47c47a0")
    public static final int kStatusFrame_AnalogTempVbat = CanTalonJNI.CanTalonSRX_kStatusFrame_AnalogTempVbat_get();

    @objid ("c47ab780-96cf-4e80-9ac6-7df7ae6c200c")
    protected CanTalonSRX(long cPtr, boolean cMemoryOwn) {
        super(CanTalonJNI.CanTalonSRX_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    @objid ("76de144b-523d-4cc7-b4fd-6d9147890ce7")
    protected static long getCPtr(CanTalonSRX obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    @objid ("6c988a01-1224-4d88-a0e2-19470ad255eb")
    protected void finalize() {
        delete();
    }

    @objid ("ad4e85a6-ff69-47ec-9d5b-861085f6e8db")
    public synchronized void delete() {
        if (swigCPtr != 0) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            CanTalonJNI.delete_CanTalonSRX(swigCPtr);
          }
          swigCPtr = 0;
        }
        super.delete();
    }

    @objid ("db147daa-fa7b-48a2-b636-7768ef2450ad")
    public CanTalonSRX(int deviceNumber, int controlPeriodMs) {
        this(CanTalonJNI.new_CanTalonSRX__SWIG_0(deviceNumber, controlPeriodMs), true);
    }

    @objid ("ed633a5f-51bf-48f8-9b1e-6737006a3c4d")
    public CanTalonSRX(int deviceNumber) {
        this(CanTalonJNI.new_CanTalonSRX__SWIG_1(deviceNumber), true);
    }

    @objid ("d795485a-5fdb-4d69-8f7e-579f2f50e752")
    public CanTalonSRX() {
        this(CanTalonJNI.new_CanTalonSRX__SWIG_2(), true);
    }

    @objid ("7a9790ab-02e4-4a38-b6d8-7a3e8c7a204a")
    public void Set(double value) {
        CanTalonJNI.CanTalonSRX_Set(swigCPtr, this, value);
    }

    @objid ("c1044621-712d-4a7f-846e-c17a8078257e")
    public SWIGTYPE_p_CTR_Code SetParam(edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t paramEnum, double value) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetParam(swigCPtr, this, paramEnum.swigValue(), value), true);
    }

    @objid ("cbd5e3f2-f23e-4f7f-90fe-6a8081f8314a")
    public SWIGTYPE_p_CTR_Code RequestParam(edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t paramEnum) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_RequestParam(swigCPtr, this, paramEnum.swigValue()), true);
    }

    @objid ("9afa4fd0-7f19-4f68-a442-15b019f6c5d4")
    public SWIGTYPE_p_CTR_Code GetParamResponse(edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t paramEnum, SWIGTYPE_p_double value) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetParamResponse(swigCPtr, this, paramEnum.swigValue(), SWIGTYPE_p_double.getCPtr(value)), true);
    }

    @objid ("5f36bcb2-4e17-4391-b16c-a99a98481fdf")
    public SWIGTYPE_p_CTR_Code GetParamResponseInt32(edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t paramEnum, SWIGTYPE_p_int value) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetParamResponseInt32(swigCPtr, this, paramEnum.swigValue(), SWIGTYPE_p_int.getCPtr(value)), true);
    }

    @objid ("39728b0a-a9c5-4fbe-a947-2c59aca07d4f")
    public SWIGTYPE_p_CTR_Code SetPgain(long slotIdx, double gain) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetPgain(swigCPtr, this, slotIdx, gain), true);
    }

    @objid ("e6a61c8f-08a0-405f-9bcf-72b8f7cadfda")
    public SWIGTYPE_p_CTR_Code SetIgain(long slotIdx, double gain) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetIgain(swigCPtr, this, slotIdx, gain), true);
    }

    @objid ("9168d78f-9844-42ec-b31c-fdfc22ad4521")
    public SWIGTYPE_p_CTR_Code SetDgain(long slotIdx, double gain) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetDgain(swigCPtr, this, slotIdx, gain), true);
    }

    @objid ("3d60fdb7-eb69-48aa-a17e-05cc44c1245b")
    public SWIGTYPE_p_CTR_Code SetFgain(long slotIdx, double gain) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetFgain(swigCPtr, this, slotIdx, gain), true);
    }

    @objid ("0307c5d8-eea9-46a3-8c60-6ad18a8e9eaf")
    public SWIGTYPE_p_CTR_Code SetIzone(long slotIdx, int zone) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetIzone(swigCPtr, this, slotIdx, zone), true);
    }

    @objid ("31c0aa71-a3ae-4fcb-a676-8902fc7da8d1")
    public SWIGTYPE_p_CTR_Code SetCloseLoopRampRate(long slotIdx, int closeLoopRampRate) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetCloseLoopRampRate(swigCPtr, this, slotIdx, closeLoopRampRate), true);
    }

    @objid ("a2add29d-bf7d-4ed1-80b8-55c26a9f2fbc")
    public SWIGTYPE_p_CTR_Code SetSensorPosition(int pos) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetSensorPosition(swigCPtr, this, pos), true);
    }

    @objid ("d3781c2f-f453-49c7-a0e0-6eab67a30d44")
    public SWIGTYPE_p_CTR_Code SetForwardSoftLimit(int forwardLimit) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetForwardSoftLimit(swigCPtr, this, forwardLimit), true);
    }

    @objid ("e9af2979-04b4-4511-a15d-87d4724ec2ad")
    public SWIGTYPE_p_CTR_Code SetReverseSoftLimit(int reverseLimit) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetReverseSoftLimit(swigCPtr, this, reverseLimit), true);
    }

    @objid ("f3268606-8d0e-4201-949d-1db6f2e8fa50")
    public SWIGTYPE_p_CTR_Code SetForwardSoftEnable(int enable) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetForwardSoftEnable(swigCPtr, this, enable), true);
    }

    @objid ("1d9a304b-c5ed-4161-8d9d-215e0a26c020")
    public SWIGTYPE_p_CTR_Code SetReverseSoftEnable(int enable) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetReverseSoftEnable(swigCPtr, this, enable), true);
    }

    @objid ("dfb61447-b102-4189-b51a-a179ab35e2b7")
    public SWIGTYPE_p_CTR_Code GetPgain(long slotIdx, SWIGTYPE_p_double gain) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetPgain(swigCPtr, this, slotIdx, SWIGTYPE_p_double.getCPtr(gain)), true);
    }

    @objid ("aba22265-5fd8-4af4-8c8a-b514b076a0db")
    public SWIGTYPE_p_CTR_Code GetIgain(long slotIdx, SWIGTYPE_p_double gain) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetIgain(swigCPtr, this, slotIdx, SWIGTYPE_p_double.getCPtr(gain)), true);
    }

    @objid ("2613dd78-660b-4b23-8d18-bc6ede30303d")
    public SWIGTYPE_p_CTR_Code GetDgain(long slotIdx, SWIGTYPE_p_double gain) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetDgain(swigCPtr, this, slotIdx, SWIGTYPE_p_double.getCPtr(gain)), true);
    }

    @objid ("12c0be1d-412e-470b-95a4-a633178dd23f")
    public SWIGTYPE_p_CTR_Code GetFgain(long slotIdx, SWIGTYPE_p_double gain) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFgain(swigCPtr, this, slotIdx, SWIGTYPE_p_double.getCPtr(gain)), true);
    }

    @objid ("ef252366-e940-4b47-8baa-99209ad2aee8")
    public SWIGTYPE_p_CTR_Code GetIzone(long slotIdx, SWIGTYPE_p_int zone) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetIzone(swigCPtr, this, slotIdx, SWIGTYPE_p_int.getCPtr(zone)), true);
    }

    @objid ("ea7c9c20-56e3-4ea8-ad3a-e8d99d6070b9")
    public SWIGTYPE_p_CTR_Code GetCloseLoopRampRate(long slotIdx, SWIGTYPE_p_int closeLoopRampRate) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetCloseLoopRampRate(swigCPtr, this, slotIdx, SWIGTYPE_p_int.getCPtr(closeLoopRampRate)), true);
    }

    @objid ("a82766a7-c65f-49c3-a5f0-c76e693ffdfb")
    public SWIGTYPE_p_CTR_Code GetForwardSoftLimit(SWIGTYPE_p_int forwardLimit) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetForwardSoftLimit(swigCPtr, this, SWIGTYPE_p_int.getCPtr(forwardLimit)), true);
    }

    @objid ("d05c3741-3cd1-4920-bad9-8f46aa1717e7")
    public SWIGTYPE_p_CTR_Code GetReverseSoftLimit(SWIGTYPE_p_int reverseLimit) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetReverseSoftLimit(swigCPtr, this, SWIGTYPE_p_int.getCPtr(reverseLimit)), true);
    }

    @objid ("fc0840e9-004a-4106-b061-0d0514978d5a")
    public SWIGTYPE_p_CTR_Code GetForwardSoftEnable(SWIGTYPE_p_int enable) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetForwardSoftEnable(swigCPtr, this, SWIGTYPE_p_int.getCPtr(enable)), true);
    }

    @objid ("ca0cc33f-5e29-4709-915d-418a25d2b4de")
    public SWIGTYPE_p_CTR_Code GetReverseSoftEnable(SWIGTYPE_p_int enable) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetReverseSoftEnable(swigCPtr, this, SWIGTYPE_p_int.getCPtr(enable)), true);
    }

    @objid ("373a91a9-bc21-4fc1-9f0d-f76884cea2c2")
    public SWIGTYPE_p_CTR_Code SetStatusFrameRate(long frameEnum, long periodMs) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetStatusFrameRate(swigCPtr, this, frameEnum, periodMs), true);
    }

    @objid ("2e58c5ea-8b60-4088-963b-fab6888d3579")
    public SWIGTYPE_p_CTR_Code ClearStickyFaults() {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_ClearStickyFaults(swigCPtr, this), true);
    }

    @objid ("c208c7e0-1c52-422f-bfbe-1e95a91e75f1")
    public SWIGTYPE_p_CTR_Code GetFault_OverTemp(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFault_OverTemp(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("80f7845c-fa25-43e1-b319-38d9a23d59c6")
    public SWIGTYPE_p_CTR_Code GetFault_UnderVoltage(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFault_UnderVoltage(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("bd73c9ed-f71b-4cbc-b9f3-2d8c653e7b95")
    public SWIGTYPE_p_CTR_Code GetFault_ForLim(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFault_ForLim(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("e8663631-a54e-435f-ab01-9cda5f651f9e")
    public SWIGTYPE_p_CTR_Code GetFault_RevLim(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFault_RevLim(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("94a605ab-fa05-476a-9965-6c563a0e2805")
    public SWIGTYPE_p_CTR_Code GetFault_HardwareFailure(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFault_HardwareFailure(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("9edd78ab-92ad-4fd2-b52f-e30c7f4a084e")
    public SWIGTYPE_p_CTR_Code GetFault_ForSoftLim(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFault_ForSoftLim(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("5334f664-1757-431a-9e54-7ee7de536385")
    public SWIGTYPE_p_CTR_Code GetFault_RevSoftLim(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFault_RevSoftLim(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("1baf7e99-ecc7-4d91-b240-899ffd4bfb20")
    public SWIGTYPE_p_CTR_Code GetStckyFault_OverTemp(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetStckyFault_OverTemp(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("87b4864e-fac1-4f83-a920-7a36a5345fa4")
    public SWIGTYPE_p_CTR_Code GetStckyFault_UnderVoltage(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetStckyFault_UnderVoltage(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("663a9046-f5fc-47b1-9ea3-0338c6f17a83")
    public SWIGTYPE_p_CTR_Code GetStckyFault_ForLim(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetStckyFault_ForLim(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("f4590b7f-45e3-497d-84f3-5d0328aa0031")
    public SWIGTYPE_p_CTR_Code GetStckyFault_RevLim(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetStckyFault_RevLim(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("a0cdb4c3-1b0d-4ca6-b467-0ef6112ec8d5")
    public SWIGTYPE_p_CTR_Code GetStckyFault_ForSoftLim(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetStckyFault_ForSoftLim(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("29da8faf-6923-4caf-a63d-752ca997e7fd")
    public SWIGTYPE_p_CTR_Code GetStckyFault_RevSoftLim(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetStckyFault_RevSoftLim(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("e107df6a-105c-484d-ac24-744f870d50f7")
    public SWIGTYPE_p_CTR_Code GetAppliedThrottle(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetAppliedThrottle(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("b38df597-c104-4077-bec8-f20ed60c7c98")
    public SWIGTYPE_p_CTR_Code GetCloseLoopErr(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetCloseLoopErr(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("76b622f9-2134-4162-9ff7-d3f6053e0b7f")
    public SWIGTYPE_p_CTR_Code GetFeedbackDeviceSelect(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFeedbackDeviceSelect(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("10636d1e-ff01-461e-ad3b-e5f307f91d0f")
    public SWIGTYPE_p_CTR_Code GetModeSelect(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetModeSelect(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("ad6f9b14-09b2-4929-96d5-f173957500c1")
    public SWIGTYPE_p_CTR_Code GetLimitSwitchEn(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetLimitSwitchEn(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("41e4da3d-14fb-4571-b4df-6b007efe5d28")
    public SWIGTYPE_p_CTR_Code GetLimitSwitchClosedFor(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetLimitSwitchClosedFor(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("5ae09359-e12f-4276-9bfb-e407af90c141")
    public SWIGTYPE_p_CTR_Code GetLimitSwitchClosedRev(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetLimitSwitchClosedRev(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("55ebef1b-15a8-48c0-aea1-e36c56db77af")
    public SWIGTYPE_p_CTR_Code GetSensorPosition(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetSensorPosition(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("ea9f8df2-052a-4882-b772-04ec1a5a2975")
    public SWIGTYPE_p_CTR_Code GetSensorVelocity(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetSensorVelocity(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("079a87d9-e432-4cf1-9e5b-8e0ac35b4a67")
    public SWIGTYPE_p_CTR_Code GetCurrent(SWIGTYPE_p_double param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetCurrent(swigCPtr, this, SWIGTYPE_p_double.getCPtr(param)), true);
    }

    @objid ("bf8bf9e3-bf91-4c9b-bf42-c5a64dc0f7d3")
    public SWIGTYPE_p_CTR_Code GetBrakeIsEnabled(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetBrakeIsEnabled(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("7756d7ac-b212-4d6e-a141-c6618c000cf6")
    public SWIGTYPE_p_CTR_Code GetEncPosition(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetEncPosition(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("a1c0ca28-a49f-4a5b-9531-a35a48f5e10a")
    public SWIGTYPE_p_CTR_Code GetEncVel(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetEncVel(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("c287b47e-9e62-45a4-a859-5cbf9527a348")
    public SWIGTYPE_p_CTR_Code GetEncIndexRiseEvents(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetEncIndexRiseEvents(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("eed5e58f-66f4-4279-aae1-5c296eee0674")
    public SWIGTYPE_p_CTR_Code GetQuadApin(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetQuadApin(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("3df5097f-839b-45f2-bb4b-62d328c57720")
    public SWIGTYPE_p_CTR_Code GetQuadBpin(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetQuadBpin(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("307761b3-1b67-4cab-8638-530f04da9e97")
    public SWIGTYPE_p_CTR_Code GetQuadIdxpin(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetQuadIdxpin(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("f6279368-c9b9-40fc-abee-b25c1f8b3185")
    public SWIGTYPE_p_CTR_Code GetAnalogInWithOv(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetAnalogInWithOv(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("ae6eed15-2579-4ed8-ac1c-cf441b92f196")
    public SWIGTYPE_p_CTR_Code GetAnalogInVel(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetAnalogInVel(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("ec2a6f88-2833-4c5e-8f68-1a39f87f43cc")
    public SWIGTYPE_p_CTR_Code GetTemp(SWIGTYPE_p_double param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetTemp(swigCPtr, this, SWIGTYPE_p_double.getCPtr(param)), true);
    }

    @objid ("d6d5b7cd-9de5-453b-bc4f-236bec2f062a")
    public SWIGTYPE_p_CTR_Code GetBatteryV(SWIGTYPE_p_double param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetBatteryV(swigCPtr, this, SWIGTYPE_p_double.getCPtr(param)), true);
    }

    @objid ("0ca72db2-ff20-481c-9c69-d0515e5de0ba")
    public SWIGTYPE_p_CTR_Code GetResetCount(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetResetCount(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("2cbfbea1-bdee-4762-ba59-e639bdd909c3")
    public SWIGTYPE_p_CTR_Code GetResetFlags(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetResetFlags(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("32279098-5ff4-4737-ad79-1ff8a061897f")
    public SWIGTYPE_p_CTR_Code GetFirmVers(SWIGTYPE_p_int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_GetFirmVers(swigCPtr, this, SWIGTYPE_p_int.getCPtr(param)), true);
    }

    @objid ("2b9cbb50-a7c9-443c-afea-02539975d1ee")
    public SWIGTYPE_p_CTR_Code SetDemand(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetDemand(swigCPtr, this, param), true);
    }

    @objid ("ca99ca24-35e0-42c2-a4f1-26c3099985c8")
    public SWIGTYPE_p_CTR_Code SetOverrideLimitSwitchEn(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetOverrideLimitSwitchEn(swigCPtr, this, param), true);
    }

    @objid ("4afe25c3-ac19-41d0-9edd-d49b5c7948ef")
    public SWIGTYPE_p_CTR_Code SetFeedbackDeviceSelect(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetFeedbackDeviceSelect(swigCPtr, this, param), true);
    }

    @objid ("2a5d331f-ae94-4e11-b59b-49c8ff70b6a9")
    public SWIGTYPE_p_CTR_Code SetRevMotDuringCloseLoopEn(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetRevMotDuringCloseLoopEn(swigCPtr, this, param), true);
    }

    @objid ("a93a0e4b-3a7b-4ca8-8929-044b5c14a32c")
    public SWIGTYPE_p_CTR_Code SetOverrideBrakeType(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetOverrideBrakeType(swigCPtr, this, param), true);
    }

    @objid ("c56e072d-6a7f-4ec4-8b3f-e1a104f1d4b4")
    public SWIGTYPE_p_CTR_Code SetModeSelect(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetModeSelect(swigCPtr, this, param), true);
    }

    @objid ("b80ecab9-65f7-42b5-8b09-01fd937df30c")
    public SWIGTYPE_p_CTR_Code SetProfileSlotSelect(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetProfileSlotSelect(swigCPtr, this, param), true);
    }

    @objid ("8c33c8bf-ef79-42b9-b2b3-cde7af8f7289")
    public SWIGTYPE_p_CTR_Code SetRampThrottle(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetRampThrottle(swigCPtr, this, param), true);
    }

    @objid ("224bd8c8-9397-4fe9-b451-28010fb3abe8")
    public SWIGTYPE_p_CTR_Code SetRevFeedbackSensor(int param) {
        return new SWIGTYPE_p_CTR_Code(CanTalonJNI.CanTalonSRX_SetRevFeedbackSensor(swigCPtr, this, param), true);
    }

    @objid ("4b74c893-df57-4bdd-b19c-abe59e10f350")
    public static final class param_t {
        @objid ("f3d6afa1-aa76-4589-89f7-9f6e790cd5b0")
        private static int swigNext = 0;

        @objid ("efb9ca20-f7ab-459a-8050-3f0717af7b39")
        private final int swigValue;

        @objid ("74db4550-8e38-4dd8-b739-0c6d6e48900c")
        private final String swigName;

        @objid ("aacb375f-87a3-4786-8f83-0e9a8ac3f9c5")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot0_P = new CanTalonSRX.param_t("eProfileParamSlot0_P", CanTalonJNI.CanTalonSRX_eProfileParamSlot0_P_get());

        @objid ("8103279f-6076-4ac7-8531-b59e6a6ab3b9")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot0_I = new CanTalonSRX.param_t("eProfileParamSlot0_I", CanTalonJNI.CanTalonSRX_eProfileParamSlot0_I_get());

        @objid ("f4fa28d4-c1d5-4309-9c80-c8403349da93")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot0_D = new CanTalonSRX.param_t("eProfileParamSlot0_D", CanTalonJNI.CanTalonSRX_eProfileParamSlot0_D_get());

        @objid ("81259424-b0ee-45f5-931c-c10406dcde0c")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot0_F = new CanTalonSRX.param_t("eProfileParamSlot0_F", CanTalonJNI.CanTalonSRX_eProfileParamSlot0_F_get());

        @objid ("ff863c07-ea7c-4ff1-a4ac-7ab82dbaed60")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot0_IZone = new CanTalonSRX.param_t("eProfileParamSlot0_IZone", CanTalonJNI.CanTalonSRX_eProfileParamSlot0_IZone_get());

        @objid ("e93a5d97-28b9-4617-b36c-94124bc8e21b")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot0_CloseLoopRampRate = new CanTalonSRX.param_t("eProfileParamSlot0_CloseLoopRampRate", CanTalonJNI.CanTalonSRX_eProfileParamSlot0_CloseLoopRampRate_get());

        @objid ("0255dbf9-4d77-4963-a426-9c8e90dd6a9c")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot1_P = new CanTalonSRX.param_t("eProfileParamSlot1_P", CanTalonJNI.CanTalonSRX_eProfileParamSlot1_P_get());

        @objid ("28198639-2f68-422c-b96b-5fda3c553801")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot1_I = new CanTalonSRX.param_t("eProfileParamSlot1_I", CanTalonJNI.CanTalonSRX_eProfileParamSlot1_I_get());

        @objid ("86ad908b-391e-49bb-824c-64b5ad4e173e")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot1_D = new CanTalonSRX.param_t("eProfileParamSlot1_D", CanTalonJNI.CanTalonSRX_eProfileParamSlot1_D_get());

        @objid ("a8a497c8-6e2c-412d-98e9-801a9ce8237d")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot1_F = new CanTalonSRX.param_t("eProfileParamSlot1_F", CanTalonJNI.CanTalonSRX_eProfileParamSlot1_F_get());

        @objid ("6f03a184-af84-411c-9f67-68ccbd2ff608")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot1_IZone = new CanTalonSRX.param_t("eProfileParamSlot1_IZone", CanTalonJNI.CanTalonSRX_eProfileParamSlot1_IZone_get());

        @objid ("ae22a40c-4603-4445-a93b-be77d5c9f567")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSlot1_CloseLoopRampRate = new CanTalonSRX.param_t("eProfileParamSlot1_CloseLoopRampRate", CanTalonJNI.CanTalonSRX_eProfileParamSlot1_CloseLoopRampRate_get());

        @objid ("3b4cd327-d2d0-46e3-95c2-bd399c21239f")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSoftLimitForThreshold = new CanTalonSRX.param_t("eProfileParamSoftLimitForThreshold", CanTalonJNI.CanTalonSRX_eProfileParamSoftLimitForThreshold_get());

        @objid ("823e1812-4564-40ec-9abe-ee2faef410a6")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSoftLimitRevThreshold = new CanTalonSRX.param_t("eProfileParamSoftLimitRevThreshold", CanTalonJNI.CanTalonSRX_eProfileParamSoftLimitRevThreshold_get());

        @objid ("13271677-10ae-4438-943a-bfa9da94c130")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSoftLimitForEnable = new CanTalonSRX.param_t("eProfileParamSoftLimitForEnable", CanTalonJNI.CanTalonSRX_eProfileParamSoftLimitForEnable_get());

        @objid ("83643c19-baae-42ae-89da-9accfe2b2b7a")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileParamSoftLimitRevEnable = new CanTalonSRX.param_t("eProfileParamSoftLimitRevEnable", CanTalonJNI.CanTalonSRX_eProfileParamSoftLimitRevEnable_get());

        @objid ("de34c0f7-9fd3-4732-ad15-fc9981aaa067")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eOnBoot_BrakeMode = new CanTalonSRX.param_t("eOnBoot_BrakeMode", CanTalonJNI.CanTalonSRX_eOnBoot_BrakeMode_get());

        @objid ("2c874789-ae41-47bb-9c94-db9894a88512")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eOnBoot_LimitSwitch_Forward_NormallyClosed = new CanTalonSRX.param_t("eOnBoot_LimitSwitch_Forward_NormallyClosed", CanTalonJNI.CanTalonSRX_eOnBoot_LimitSwitch_Forward_NormallyClosed_get());

        @objid ("e8a540f8-5578-4ac9-9627-c447ea883d58")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eOnBoot_LimitSwitch_Reverse_NormallyClosed = new CanTalonSRX.param_t("eOnBoot_LimitSwitch_Reverse_NormallyClosed", CanTalonJNI.CanTalonSRX_eOnBoot_LimitSwitch_Reverse_NormallyClosed_get());

        @objid ("2623ff0d-41ca-4635-be9c-54c363ad3147")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eOnBoot_LimitSwitch_Forward_Disable = new CanTalonSRX.param_t("eOnBoot_LimitSwitch_Forward_Disable", CanTalonJNI.CanTalonSRX_eOnBoot_LimitSwitch_Forward_Disable_get());

        @objid ("4fc84e02-2338-425b-9edd-d02e17c92043")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eOnBoot_LimitSwitch_Reverse_Disable = new CanTalonSRX.param_t("eOnBoot_LimitSwitch_Reverse_Disable", CanTalonJNI.CanTalonSRX_eOnBoot_LimitSwitch_Reverse_Disable_get());

        @objid ("adf3fad8-587a-455d-b7ba-a6ed5889be12")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFault_OverTemp = new CanTalonSRX.param_t("eFault_OverTemp", CanTalonJNI.CanTalonSRX_eFault_OverTemp_get());

        @objid ("8d794d42-adc3-493b-8ab7-f43b4e5ba693")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFault_UnderVoltage = new CanTalonSRX.param_t("eFault_UnderVoltage", CanTalonJNI.CanTalonSRX_eFault_UnderVoltage_get());

        @objid ("d01670ab-b50e-47f8-9bfb-bf702c9bed50")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFault_ForLim = new CanTalonSRX.param_t("eFault_ForLim", CanTalonJNI.CanTalonSRX_eFault_ForLim_get());

        @objid ("6a225136-85de-4d86-85e8-4083eb921e22")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFault_RevLim = new CanTalonSRX.param_t("eFault_RevLim", CanTalonJNI.CanTalonSRX_eFault_RevLim_get());

        @objid ("3109fea6-f9f1-46d8-93c8-546390257feb")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFault_HardwareFailure = new CanTalonSRX.param_t("eFault_HardwareFailure", CanTalonJNI.CanTalonSRX_eFault_HardwareFailure_get());

        @objid ("83acb76d-981a-47a4-994c-e5ab600b26f9")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFault_ForSoftLim = new CanTalonSRX.param_t("eFault_ForSoftLim", CanTalonJNI.CanTalonSRX_eFault_ForSoftLim_get());

        @objid ("616f07d5-f5df-42c8-b27d-19ff294513c5")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFault_RevSoftLim = new CanTalonSRX.param_t("eFault_RevSoftLim", CanTalonJNI.CanTalonSRX_eFault_RevSoftLim_get());

        @objid ("5b2411a5-35e3-43d6-b91b-5b67767540c8")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eStckyFault_OverTemp = new CanTalonSRX.param_t("eStckyFault_OverTemp", CanTalonJNI.CanTalonSRX_eStckyFault_OverTemp_get());

        @objid ("663ff13c-f20a-40bf-bc6d-057a6c4d2812")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eStckyFault_UnderVoltage = new CanTalonSRX.param_t("eStckyFault_UnderVoltage", CanTalonJNI.CanTalonSRX_eStckyFault_UnderVoltage_get());

        @objid ("74228a31-919e-483f-afbd-0383783d07ce")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eStckyFault_ForLim = new CanTalonSRX.param_t("eStckyFault_ForLim", CanTalonJNI.CanTalonSRX_eStckyFault_ForLim_get());

        @objid ("dddabf46-1a48-4b1a-b208-2154ff361d39")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eStckyFault_RevLim = new CanTalonSRX.param_t("eStckyFault_RevLim", CanTalonJNI.CanTalonSRX_eStckyFault_RevLim_get());

        @objid ("5f69f742-4310-42e1-a8ee-3399fc13ef47")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eStckyFault_ForSoftLim = new CanTalonSRX.param_t("eStckyFault_ForSoftLim", CanTalonJNI.CanTalonSRX_eStckyFault_ForSoftLim_get());

        @objid ("fb4bbaf6-96f7-49f4-a006-81ae29683d0a")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eStckyFault_RevSoftLim = new CanTalonSRX.param_t("eStckyFault_RevSoftLim", CanTalonJNI.CanTalonSRX_eStckyFault_RevSoftLim_get());

        @objid ("371701c5-2bea-4b91-b852-21020f7f1a50")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eAppliedThrottle = new CanTalonSRX.param_t("eAppliedThrottle", CanTalonJNI.CanTalonSRX_eAppliedThrottle_get());

        @objid ("d6c53415-e02b-4117-b67e-ff4019360437")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eCloseLoopErr = new CanTalonSRX.param_t("eCloseLoopErr", CanTalonJNI.CanTalonSRX_eCloseLoopErr_get());

        @objid ("dd1bf626-a78d-4627-83fa-c887e0531268")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFeedbackDeviceSelect = new CanTalonSRX.param_t("eFeedbackDeviceSelect", CanTalonJNI.CanTalonSRX_eFeedbackDeviceSelect_get());

        @objid ("8718f6e8-5448-4dc2-9cd5-e087fb98cf8c")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eRevMotDuringCloseLoopEn = new CanTalonSRX.param_t("eRevMotDuringCloseLoopEn", CanTalonJNI.CanTalonSRX_eRevMotDuringCloseLoopEn_get());

        @objid ("b5c22a11-5e35-4a8a-a1c3-ff98b0070b17")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eModeSelect = new CanTalonSRX.param_t("eModeSelect", CanTalonJNI.CanTalonSRX_eModeSelect_get());

        @objid ("8b981f24-d935-490d-8f38-1eb44cf6ec9d")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eProfileSlotSelect = new CanTalonSRX.param_t("eProfileSlotSelect", CanTalonJNI.CanTalonSRX_eProfileSlotSelect_get());

        @objid ("7fb38cc6-a94a-423c-901e-3269b9c04517")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eRampThrottle = new CanTalonSRX.param_t("eRampThrottle", CanTalonJNI.CanTalonSRX_eRampThrottle_get());

        @objid ("abcbba61-bb24-4304-9beb-cf62a4855094")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eRevFeedbackSensor = new CanTalonSRX.param_t("eRevFeedbackSensor", CanTalonJNI.CanTalonSRX_eRevFeedbackSensor_get());

        @objid ("a75dea44-aab3-4786-9b2e-3e3e5c743127")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eLimitSwitchEn = new CanTalonSRX.param_t("eLimitSwitchEn", CanTalonJNI.CanTalonSRX_eLimitSwitchEn_get());

        @objid ("d9af5640-4c0e-453e-89a8-e8a17c034ca5")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eLimitSwitchClosedFor = new CanTalonSRX.param_t("eLimitSwitchClosedFor", CanTalonJNI.CanTalonSRX_eLimitSwitchClosedFor_get());

        @objid ("e8c468f9-1381-4cd1-b129-4a1d0b321964")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eLimitSwitchClosedRev = new CanTalonSRX.param_t("eLimitSwitchClosedRev", CanTalonJNI.CanTalonSRX_eLimitSwitchClosedRev_get());

        @objid ("3e9ff72d-439c-4ad4-99a3-d83e39f0d3eb")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eSensorPosition = new CanTalonSRX.param_t("eSensorPosition", CanTalonJNI.CanTalonSRX_eSensorPosition_get());

        @objid ("e64bbb1d-3185-44ce-850a-061cf2dfbcfa")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eSensorVelocity = new CanTalonSRX.param_t("eSensorVelocity", CanTalonJNI.CanTalonSRX_eSensorVelocity_get());

        @objid ("c5b28c0c-6cc4-4e4e-989d-bf54be17ec68")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eCurrent = new CanTalonSRX.param_t("eCurrent", CanTalonJNI.CanTalonSRX_eCurrent_get());

        @objid ("ef278e20-f3b9-4f50-aa40-a2516af53bfe")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eBrakeIsEnabled = new CanTalonSRX.param_t("eBrakeIsEnabled", CanTalonJNI.CanTalonSRX_eBrakeIsEnabled_get());

        @objid ("48948cb1-61ba-4d4a-b1c5-734abffdcc7d")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eEncPosition = new CanTalonSRX.param_t("eEncPosition", CanTalonJNI.CanTalonSRX_eEncPosition_get());

        @objid ("8fc66291-9680-407c-bfc2-af1742737283")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eEncVel = new CanTalonSRX.param_t("eEncVel", CanTalonJNI.CanTalonSRX_eEncVel_get());

        @objid ("965062cb-30a1-4622-ab54-e3017a8e807d")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eEncIndexRiseEvents = new CanTalonSRX.param_t("eEncIndexRiseEvents", CanTalonJNI.CanTalonSRX_eEncIndexRiseEvents_get());

        @objid ("c2f2f4a3-0bdb-4ef9-8ac1-bf00f29599b8")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eQuadApin = new CanTalonSRX.param_t("eQuadApin", CanTalonJNI.CanTalonSRX_eQuadApin_get());

        @objid ("14d0f670-8b95-446e-ab33-c7e2f3c4ab21")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eQuadBpin = new CanTalonSRX.param_t("eQuadBpin", CanTalonJNI.CanTalonSRX_eQuadBpin_get());

        @objid ("1542f802-79df-400a-b89c-ac1cc33b53a3")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eQuadIdxpin = new CanTalonSRX.param_t("eQuadIdxpin", CanTalonJNI.CanTalonSRX_eQuadIdxpin_get());

        @objid ("1668db19-1b70-48bc-89c2-0314f36cbfb0")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eAnalogInWithOv = new CanTalonSRX.param_t("eAnalogInWithOv", CanTalonJNI.CanTalonSRX_eAnalogInWithOv_get());

        @objid ("d706e9e5-aaa3-447c-969a-fbe714fbe4c5")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eAnalogInVel = new CanTalonSRX.param_t("eAnalogInVel", CanTalonJNI.CanTalonSRX_eAnalogInVel_get());

        @objid ("a080c919-a21c-49f6-9802-4228c85e67bd")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eTemp = new CanTalonSRX.param_t("eTemp", CanTalonJNI.CanTalonSRX_eTemp_get());

        @objid ("d5ce4c5d-771d-4ebe-9a29-d0335833acc8")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eBatteryV = new CanTalonSRX.param_t("eBatteryV", CanTalonJNI.CanTalonSRX_eBatteryV_get());

        @objid ("815f0262-8b76-422c-9a48-c3520de80cc1")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eResetCount = new CanTalonSRX.param_t("eResetCount", CanTalonJNI.CanTalonSRX_eResetCount_get());

        @objid ("7e05f171-eaa1-4abf-ba77-1f149dfb2c3a")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eResetFlags = new CanTalonSRX.param_t("eResetFlags", CanTalonJNI.CanTalonSRX_eResetFlags_get());

        @objid ("f4608c96-3bc4-45b4-a130-6bf69ae90700")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eFirmVers = new CanTalonSRX.param_t("eFirmVers", CanTalonJNI.CanTalonSRX_eFirmVers_get());

        @objid ("4a7309e9-4092-4fa0-9ff7-e084fd5d8199")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eSettingsChanged = new CanTalonSRX.param_t("eSettingsChanged", CanTalonJNI.CanTalonSRX_eSettingsChanged_get());

        @objid ("2bec5974-7543-433d-a501-e18d7b9fe3e6")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t eQuadFilterEn = new CanTalonSRX.param_t("eQuadFilterEn", CanTalonJNI.CanTalonSRX_eQuadFilterEn_get());

        @objid ("96d53f12-2c20-4acf-9b36-95feba1402a3")
        public static final edu.wpi.first.wpilibj.hal.CanTalonSRX.param_t ePidIaccum = new CanTalonSRX.param_t("ePidIaccum", CanTalonJNI.CanTalonSRX_ePidIaccum_get());

        @objid ("ac3ed11c-62e1-4728-ae9f-488508db1e44")
        private static param_t[] swigValues = { eProfileParamSlot0_P, eProfileParamSlot0_I, eProfileParamSlot0_D, eProfileParamSlot0_F, eProfileParamSlot0_IZone, eProfileParamSlot0_CloseLoopRampRate, eProfileParamSlot1_P, eProfileParamSlot1_I, eProfileParamSlot1_D, eProfileParamSlot1_F, eProfileParamSlot1_IZone, eProfileParamSlot1_CloseLoopRampRate, eProfileParamSoftLimitForThreshold, eProfileParamSoftLimitRevThreshold, eProfileParamSoftLimitForEnable, eProfileParamSoftLimitRevEnable, eOnBoot_BrakeMode, eOnBoot_LimitSwitch_Forward_NormallyClosed, eOnBoot_LimitSwitch_Reverse_NormallyClosed, eOnBoot_LimitSwitch_Forward_Disable, eOnBoot_LimitSwitch_Reverse_Disable, eFault_OverTemp, eFault_UnderVoltage, eFault_ForLim, eFault_RevLim, eFault_HardwareFailure, eFault_ForSoftLim, eFault_RevSoftLim, eStckyFault_OverTemp, eStckyFault_UnderVoltage, eStckyFault_ForLim, eStckyFault_RevLim, eStckyFault_ForSoftLim, eStckyFault_RevSoftLim, eAppliedThrottle, eCloseLoopErr, eFeedbackDeviceSelect, eRevMotDuringCloseLoopEn, eModeSelect, eProfileSlotSelect, eRampThrottle, eRevFeedbackSensor, eLimitSwitchEn, eLimitSwitchClosedFor, eLimitSwitchClosedRev, eSensorPosition, eSensorVelocity, eCurrent, eBrakeIsEnabled, eEncPosition, eEncVel, eEncIndexRiseEvents, eQuadApin, eQuadBpin, eQuadIdxpin, eAnalogInWithOv, eAnalogInVel, eTemp, eBatteryV, eResetCount, eResetFlags, eFirmVers, eSettingsChanged, eQuadFilterEn, ePidIaccum };

        @objid ("35dacbb3-d8f0-4099-afad-eb06dafea166")
        public final int swigValue() {
            return swigValue;
        }

        @objid ("f12863f1-858a-44c9-b3e6-8197b1df15d2")
        public String toString() {
            return swigName;
        }

        @objid ("d97db8b0-4e76-4854-9444-067e05d3b8fc")
        public static param_t swigToEnum(int swigValue) {
            if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
              return swigValues[swigValue];
            for (int i = 0; i < swigValues.length; i++)
              if (swigValues[i].swigValue == swigValue)
                return swigValues[i];
            throw new IllegalArgumentException("No enum " + param_t.class + " with value " + swigValue);
        }

        @objid ("9320d78b-85f7-447c-8b47-f5897264e6ac")
        private param_t(String swigName) {
            this.swigName = swigName;
            this.swigValue = swigNext++;
        }

        @objid ("e3899744-e897-4380-8c79-0ade3fe35024")
        private param_t(String swigName, int swigValue) {
            this.swigName = swigName;
            this.swigValue = swigValue;
            swigNext = swigValue+1;
        }

        @objid ("fd045091-b300-4e5d-a21d-b8ca69fb1ec8")
        private param_t(String swigName, param_t swigEnum) {
            this.swigName = swigName;
            this.swigValue = swigEnum.swigValue;
            swigNext = this.swigValue+1;
        }

    }

}
