/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("9bf6ad22-f106-4539-a589-2b40859525b3")
public class CanTalonJNI {
    @objid ("bbadfc5e-580e-4190-a6d4-e5c4ed13bd1e")
    public static final native long new_doublep();

    @objid ("901daea5-088d-44e6-8db0-833bed976394")
    public static final native long copy_doublep(double jarg1);

    @objid ("770b5009-d60d-4753-8409-39d14f08fbc1")
    public static final native void delete_doublep(long jarg1);

    @objid ("50166acd-608a-449a-ad3b-9cbb1f9a6163")
    public static final native void doublep_assign(long jarg1, double jarg2);

    @objid ("63b76213-642f-4436-913d-7a434a574675")
    public static final native double doublep_value(long jarg1);

    @objid ("516d5a2c-15c7-45fe-9bd8-2b34ad895c3b")
    public static final native long new_intp();

    @objid ("80e5dfd8-a9af-41e6-b1cd-c34ff59812e0")
    public static final native long copy_intp(int jarg1);

    @objid ("3460aabb-a4ee-49d4-9bb1-a33924a09ae4")
    public static final native void delete_intp(long jarg1);

    @objid ("ddf923c8-456d-4dae-81d8-a38ffcc2cad5")
    public static final native void intp_assign(long jarg1, int jarg2);

    @objid ("339053ce-9993-4524-84df-12e365e67b5d")
    public static final native int intp_value(long jarg1);

    @objid ("502af4a8-411f-49fa-aaf5-335c36cdac99")
    public static final native long new_uint32_tp();

    @objid ("6c704f60-8431-4c0e-af91-84509373c438")
    public static final native long copy_uint32_tp(long jarg1);

    @objid ("f37e1271-24c7-4c81-b1cb-2bc1a233b758")
    public static final native void delete_uint32_tp(long jarg1);

    @objid ("75733d9c-a740-4400-9c6c-7ee7552a0bfe")
    public static final native void uint32_tp_assign(long jarg1, long jarg2);

    @objid ("a12ac6ac-aeb9-4332-9211-abe07946590a")
    public static final native long uint32_tp_value(long jarg1);

    @objid ("8de3e7a2-4924-4bf8-84e3-d3dab9439b55")
    public static final native long new_int32_tp();

    @objid ("76493329-e8ea-4be6-84e0-552231112db6")
    public static final native long copy_int32_tp(long jarg1);

    @objid ("ba1ba837-fc99-4805-8124-1bf81b91ce4f")
    public static final native void delete_int32_tp(long jarg1);

    @objid ("2af000ed-af16-4000-a989-3671f34f8db2")
    public static final native void int32_tp_assign(long jarg1, long jarg2);

    @objid ("5459a428-c53a-4c13-9578-9c16461cc5f4")
    public static final native long int32_tp_value(long jarg1);

    @objid ("6e2c6964-ccb9-46b2-a61c-a978142b6d77")
    public static final native long new_uint8_tp();

    @objid ("a940e387-34b6-4418-abc4-ff78e00fbf39")
    public static final native long copy_uint8_tp(long jarg1);

    @objid ("655d4a49-d06d-4391-b891-6bf2bfc5a7b8")
    public static final native void delete_uint8_tp(long jarg1);

    @objid ("8378bb19-3fd4-4021-a882-98ad00ec9bb9")
    public static final native void uint8_tp_assign(long jarg1, long jarg2);

    @objid ("6333c4ed-0c1b-4a7f-b3a0-544e683002c1")
    public static final native long uint8_tp_value(long jarg1);

    @objid ("99012ce9-ccc6-42ec-86d2-5a4f9037b483")
    public static final native long new_CTR_Codep();

    @objid ("12c76d4b-32d6-4d35-8f7e-2eb9c92c03a2")
    public static final native long copy_CTR_Codep(long jarg1);

    @objid ("754152bd-e5f5-4977-b476-fcd3e18f1e1b")
    public static final native void delete_CTR_Codep(long jarg1);

    @objid ("bfdbcc15-8906-4e71-b48b-965220cbb1f0")
    public static final native void CTR_Codep_assign(long jarg1, long jarg2);

    @objid ("5cebf271-4be6-4aaf-bac5-98db57b371fd")
    public static final native long CTR_Codep_value(long jarg1);

    @objid ("75ff4dd4-1ab6-4f9a-bc0f-152177745cce")
    public static final native long new_floatp();

    @objid ("e339b7fd-133b-4932-b533-a86d748cff29")
    public static final native long copy_floatp(float jarg1);

    @objid ("b42a2973-a9c9-4106-853c-8e53e0a1534c")
    public static final native void delete_floatp(long jarg1);

    @objid ("5466d0cc-26fc-46fa-b4db-d90e0f8d5fdd")
    public static final native void floatp_assign(long jarg1, float jarg2);

    @objid ("887ef19b-f5af-4046-bc91-f8c130280ca2")
    public static final native float floatp_value(long jarg1);

    @objid ("73886b28-1385-4ead-adae-d19fe22e5db4")
    public static final native long new_CtreCanNode(long jarg1);

    @objid ("f91a3716-069c-41a4-b374-43f4192615eb")
    public static final native void delete_CtreCanNode(long jarg1);

    @objid ("35695777-5519-40bf-bea1-4a38019985d9")
    public static final native long CtreCanNode_GetDeviceNumber(long jarg1, CtreCanNode jarg1_);

    @objid ("1012e9de-cf10-4653-a152-c28e4e22ca64")
    public static final native int CanTalonSRX_kDefaultControlPeriodMs_get();

    @objid ("9831c4d4-6879-46c3-8753-d2babcc537e6")
    public static final native long new_CanTalonSRX__SWIG_0(int jarg1, int jarg2);

    @objid ("dfc77487-1fe7-4096-a14d-1b84b6e325c3")
    public static final native long new_CanTalonSRX__SWIG_1(int jarg1);

    @objid ("acfc590a-4417-43f0-ad18-b3995412695b")
    public static final native long new_CanTalonSRX__SWIG_2();

    @objid ("d9f540d5-cfe3-4890-a69a-5b6a8b52755a")
    public static final native void delete_CanTalonSRX(long jarg1);

    @objid ("05703b1e-09d3-43a9-837f-835438fb4bf1")
    public static final native void CanTalonSRX_Set(long jarg1, CanTalonSRX jarg1_, double jarg2);

    @objid ("4fa5c50c-fbc9-480e-b123-d1250ad0b2d1")
    public static final native int CanTalonSRX_kMode_DutyCycle_get();

    @objid ("685b5d7b-d559-4561-b91b-cc367e54b98e")
    public static final native int CanTalonSRX_kMode_PositionCloseLoop_get();

    @objid ("34ce4d82-5469-49ac-a82a-93f5d8a14f35")
    public static final native int CanTalonSRX_kMode_VelocityCloseLoop_get();

    @objid ("362b2cf6-6559-40ed-95d1-9118120bc67d")
    public static final native int CanTalonSRX_kMode_CurrentCloseLoop_get();

    @objid ("aaf035ed-89c1-4743-88b5-2b6193cf51c6")
    public static final native int CanTalonSRX_kMode_VoltCompen_get();

    @objid ("3fb9db75-cd53-4852-8861-593fe8b78fec")
    public static final native int CanTalonSRX_kMode_SlaveFollower_get();

    @objid ("e3d2cbd9-e7ec-4ce7-9c33-a515189e73ec")
    public static final native int CanTalonSRX_kMode_NoDrive_get();

    @objid ("8f3ad8f7-2a3c-44c3-9f61-758b5e6ff327")
    public static final native int CanTalonSRX_kLimitSwitchOverride_UseDefaultsFromFlash_get();

    @objid ("8cba56c2-8ef5-4b61-989c-640ae60b4099")
    public static final native int CanTalonSRX_kLimitSwitchOverride_DisableFwd_DisableRev_get();

    @objid ("59a2ee00-8be9-4b40-893a-9fa3706e5198")
    public static final native int CanTalonSRX_kLimitSwitchOverride_DisableFwd_EnableRev_get();

    @objid ("124bb30e-bef2-4083-85cf-6aac41db7663")
    public static final native int CanTalonSRX_kLimitSwitchOverride_EnableFwd_DisableRev_get();

    @objid ("3df9192d-4dc3-4f1f-afd2-86ff97ad7145")
    public static final native int CanTalonSRX_kLimitSwitchOverride_EnableFwd_EnableRev_get();

    @objid ("05b7a92e-5715-4c0f-b8a7-72fe7dee8334")
    public static final native int CanTalonSRX_kBrakeOverride_UseDefaultsFromFlash_get();

    @objid ("f7a7c155-0ea6-448c-9005-fbb6b7294618")
    public static final native int CanTalonSRX_kBrakeOverride_OverrideCoast_get();

    @objid ("d910377a-74b4-43ec-83f9-d75473eabe89")
    public static final native int CanTalonSRX_kBrakeOverride_OverrideBrake_get();

    @objid ("0991383a-8660-450b-9b06-b98e82173534")
    public static final native int CanTalonSRX_kFeedbackDev_DigitalQuadEnc_get();

    @objid ("57318d9e-0b58-4877-9146-62d6aa2a1317")
    public static final native int CanTalonSRX_kFeedbackDev_AnalogPot_get();

    @objid ("0559c78e-817e-45b5-a1ff-b0c7f2fe19e4")
    public static final native int CanTalonSRX_kFeedbackDev_AnalogEncoder_get();

    @objid ("fc8b37b5-f7b6-43eb-bafb-6e2ebc90afa4")
    public static final native int CanTalonSRX_kFeedbackDev_CountEveryRisingEdge_get();

    @objid ("35167321-b3f8-4094-b077-e1224304bb9b")
    public static final native int CanTalonSRX_kFeedbackDev_CountEveryFallingEdge_get();

    @objid ("cf681232-a695-4403-bfc2-a6a6d6ef0c94")
    public static final native int CanTalonSRX_kFeedbackDev_PosIsPulseWidth_get();

    @objid ("d07cf76f-858b-411f-b8fb-158abd4a3e26")
    public static final native int CanTalonSRX_kProfileSlotSelect_Slot0_get();

    @objid ("8db97c93-1800-4744-8712-4329a93fa0ea")
    public static final native int CanTalonSRX_kProfileSlotSelect_Slot1_get();

    @objid ("0d82e095-cdf3-4121-a90d-e70c85771868")
    public static final native int CanTalonSRX_kStatusFrame_General_get();

    @objid ("33b064d4-71f2-4a51-add0-52fb88990757")
    public static final native int CanTalonSRX_kStatusFrame_Feedback_get();

    @objid ("842c7a70-f00c-41cf-9dde-bea87bc6e4f6")
    public static final native int CanTalonSRX_kStatusFrame_Encoder_get();

    @objid ("1af6e0d9-ddf4-4018-a48c-a9d2b30ec179")
    public static final native int CanTalonSRX_kStatusFrame_AnalogTempVbat_get();

    @objid ("3df68065-b682-4022-b9f7-fd58440d93d4")
    public static final native int CanTalonSRX_eProfileParamSlot0_P_get();

    @objid ("b328a0aa-9c54-4774-95be-1ee2a38ecac0")
    public static final native int CanTalonSRX_eProfileParamSlot0_I_get();

    @objid ("128f54ea-d1f9-43a6-936f-220b1eac5e41")
    public static final native int CanTalonSRX_eProfileParamSlot0_D_get();

    @objid ("0b435409-e1a4-4d85-89cd-0d38890f8409")
    public static final native int CanTalonSRX_eProfileParamSlot0_F_get();

    @objid ("7aa9471d-d9dd-408c-9224-d3ce0e21b156")
    public static final native int CanTalonSRX_eProfileParamSlot0_IZone_get();

    @objid ("794d624f-61f1-41a0-bddb-af681abf1077")
    public static final native int CanTalonSRX_eProfileParamSlot0_CloseLoopRampRate_get();

    @objid ("9652ec71-b55b-4525-9012-ef56d9c62f44")
    public static final native int CanTalonSRX_eProfileParamSlot1_P_get();

    @objid ("60611f94-6838-46b3-a4b0-6c8323ccc7c8")
    public static final native int CanTalonSRX_eProfileParamSlot1_I_get();

    @objid ("a0721a00-23dc-4d0e-8453-f15438e786f3")
    public static final native int CanTalonSRX_eProfileParamSlot1_D_get();

    @objid ("48937153-4e79-49b5-b225-1b55f6819e88")
    public static final native int CanTalonSRX_eProfileParamSlot1_F_get();

    @objid ("f864d89e-749d-42a3-885e-35cc8ba5c907")
    public static final native int CanTalonSRX_eProfileParamSlot1_IZone_get();

    @objid ("fd578690-58a9-40e1-89ca-1267da425cec")
    public static final native int CanTalonSRX_eProfileParamSlot1_CloseLoopRampRate_get();

    @objid ("c0aef3d6-6996-4ed5-908d-062fc4526846")
    public static final native int CanTalonSRX_eProfileParamSoftLimitForThreshold_get();

    @objid ("eb266dae-ec17-41eb-8a59-be90ea33b2bf")
    public static final native int CanTalonSRX_eProfileParamSoftLimitRevThreshold_get();

    @objid ("0dd12194-7be1-4b1f-8f22-436454ae5525")
    public static final native int CanTalonSRX_eProfileParamSoftLimitForEnable_get();

    @objid ("9941a43c-f0e6-49c5-a533-4609cef2c00f")
    public static final native int CanTalonSRX_eProfileParamSoftLimitRevEnable_get();

    @objid ("f9405b86-7f9d-4acd-9c33-f01b39b8cd8f")
    public static final native int CanTalonSRX_eOnBoot_BrakeMode_get();

    @objid ("b5417507-09b8-4b06-a6f0-cf5e893bfb08")
    public static final native int CanTalonSRX_eOnBoot_LimitSwitch_Forward_NormallyClosed_get();

    @objid ("7b4470d4-7389-4eb8-b6aa-48af2ba484aa")
    public static final native int CanTalonSRX_eOnBoot_LimitSwitch_Reverse_NormallyClosed_get();

    @objid ("0923751f-9c8a-4fa3-a6cc-7006f6dff449")
    public static final native int CanTalonSRX_eOnBoot_LimitSwitch_Forward_Disable_get();

    @objid ("1cf762b7-cafb-4c4a-b304-f97f7d7c87f0")
    public static final native int CanTalonSRX_eOnBoot_LimitSwitch_Reverse_Disable_get();

    @objid ("b4e855e3-08bb-4afe-b20d-1171cc74d57f")
    public static final native int CanTalonSRX_eFault_OverTemp_get();

    @objid ("f3bc97b0-799e-4d0c-bddb-0ffa0b27f0a2")
    public static final native int CanTalonSRX_eFault_UnderVoltage_get();

    @objid ("3cfc3f24-76e1-4e81-9e7b-bb0733fd579c")
    public static final native int CanTalonSRX_eFault_ForLim_get();

    @objid ("c0a6c303-6a16-4c21-8d9d-4606e7f01d08")
    public static final native int CanTalonSRX_eFault_RevLim_get();

    @objid ("14759c00-2af6-4bd0-b735-14d4e26b064c")
    public static final native int CanTalonSRX_eFault_HardwareFailure_get();

    @objid ("cb3ee57b-d4b9-48db-b825-e9fd92c2a3b8")
    public static final native int CanTalonSRX_eFault_ForSoftLim_get();

    @objid ("7467b8d5-3d67-4107-9c88-cccf6dffe249")
    public static final native int CanTalonSRX_eFault_RevSoftLim_get();

    @objid ("09fd171b-be3b-4ec7-a0a7-d9aef0667103")
    public static final native int CanTalonSRX_eStckyFault_OverTemp_get();

    @objid ("a99855b3-605b-4303-8020-f3dd71d8f0ba")
    public static final native int CanTalonSRX_eStckyFault_UnderVoltage_get();

    @objid ("27039731-e8c2-48ac-89b0-87b0be65fd82")
    public static final native int CanTalonSRX_eStckyFault_ForLim_get();

    @objid ("0579eea0-dd91-4278-b797-3670ee7a7e33")
    public static final native int CanTalonSRX_eStckyFault_RevLim_get();

    @objid ("e6b6bfae-6f0f-461a-abf4-0a1007b2f315")
    public static final native int CanTalonSRX_eStckyFault_ForSoftLim_get();

    @objid ("8170e3c9-e6ec-43f4-be9c-24ee3dc6c6ae")
    public static final native int CanTalonSRX_eStckyFault_RevSoftLim_get();

    @objid ("bbb21c96-b561-4f4f-948e-b6fdf2bcc604")
    public static final native int CanTalonSRX_eAppliedThrottle_get();

    @objid ("6a3e246c-cfda-462a-85e5-b821592736bc")
    public static final native int CanTalonSRX_eCloseLoopErr_get();

    @objid ("5776c262-2c8a-469e-b1dd-8ef35775f66f")
    public static final native int CanTalonSRX_eFeedbackDeviceSelect_get();

    @objid ("dca7eaeb-3d59-49c5-adb0-20d8dffa837e")
    public static final native int CanTalonSRX_eRevMotDuringCloseLoopEn_get();

    @objid ("12a533dd-11af-4d2e-b339-1b638ea15aa2")
    public static final native int CanTalonSRX_eModeSelect_get();

    @objid ("6a5cee2d-d501-40d4-a317-d5cbcc3c8217")
    public static final native int CanTalonSRX_eProfileSlotSelect_get();

    @objid ("8fc6475d-4ecf-4321-9574-6c0601a7ba10")
    public static final native int CanTalonSRX_eRampThrottle_get();

    @objid ("2186eeb0-c6da-4e35-a070-07ff2fd83767")
    public static final native int CanTalonSRX_eRevFeedbackSensor_get();

    @objid ("d0ba929d-673b-4c8e-aa93-008cb5988e67")
    public static final native int CanTalonSRX_eLimitSwitchEn_get();

    @objid ("97400336-fff6-43ce-9715-161d8595d98b")
    public static final native int CanTalonSRX_eLimitSwitchClosedFor_get();

    @objid ("c7848553-d623-4adf-8d8f-247fcded596d")
    public static final native int CanTalonSRX_eLimitSwitchClosedRev_get();

    @objid ("3647478c-ade1-49a9-b692-b75525ddef8d")
    public static final native int CanTalonSRX_eSensorPosition_get();

    @objid ("5bc51662-7656-4a2b-bbdb-3c253bb435e0")
    public static final native int CanTalonSRX_eSensorVelocity_get();

    @objid ("39e02fea-2de0-48f0-ba92-aed585242422")
    public static final native int CanTalonSRX_eCurrent_get();

    @objid ("7648a7a7-0e93-40f6-ade4-7d62c4175051")
    public static final native int CanTalonSRX_eBrakeIsEnabled_get();

    @objid ("9cbdb047-fea5-4fab-bbe6-59ceb74065d8")
    public static final native int CanTalonSRX_eEncPosition_get();

    @objid ("34fe6c6e-fd12-4c35-afa7-43ef10607f5e")
    public static final native int CanTalonSRX_eEncVel_get();

    @objid ("f3e698d8-8d26-4f46-aa94-3b93a01bf7c5")
    public static final native int CanTalonSRX_eEncIndexRiseEvents_get();

    @objid ("1a35ae5a-47cc-4079-bad3-4eee86c4dc5b")
    public static final native int CanTalonSRX_eQuadApin_get();

    @objid ("62a68b38-ef79-4fed-a673-23e09f71dea4")
    public static final native int CanTalonSRX_eQuadBpin_get();

    @objid ("7a8eefd3-12a4-46dc-8056-a42b28480f76")
    public static final native int CanTalonSRX_eQuadIdxpin_get();

    @objid ("2d6b80c0-69ad-4601-9039-b6af1caf1052")
    public static final native int CanTalonSRX_eAnalogInWithOv_get();

    @objid ("393d4975-9e55-4fc3-9c4b-d4e73d1df8e2")
    public static final native int CanTalonSRX_eAnalogInVel_get();

    @objid ("8a6035b0-54c2-4587-9665-e9569a1d1f35")
    public static final native int CanTalonSRX_eTemp_get();

    @objid ("929b3be8-5b6b-427f-8f6d-faf2a846753f")
    public static final native int CanTalonSRX_eBatteryV_get();

    @objid ("8da52f68-1657-421f-9782-9e888e3db986")
    public static final native int CanTalonSRX_eResetCount_get();

    @objid ("1368c713-359e-4939-bc36-bd42f388d1c5")
    public static final native int CanTalonSRX_eResetFlags_get();

    @objid ("4e1cb169-de14-4947-b5a4-97e44248831a")
    public static final native int CanTalonSRX_eFirmVers_get();

    @objid ("65e540d0-eb38-4851-9249-d756a93fc2fb")
    public static final native int CanTalonSRX_eSettingsChanged_get();

    @objid ("649c169e-cb3c-4000-9f86-f98b46fbd7bf")
    public static final native int CanTalonSRX_eQuadFilterEn_get();

    @objid ("4b0a997a-a584-43b0-b104-07e8a7c9067c")
    public static final native int CanTalonSRX_ePidIaccum_get();

    @objid ("1b26f780-519f-428d-9a6f-50e667c3bc5b")
    public static final native long CanTalonSRX_SetParam(long jarg1, CanTalonSRX jarg1_, int jarg2, double jarg3);

    @objid ("b4c54e68-545a-4f49-8ea0-cf62fabda507")
    public static final native long CanTalonSRX_RequestParam(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("b5f80ca4-5309-4b55-a2b4-e8f6cccee422")
    public static final native long CanTalonSRX_GetParamResponse(long jarg1, CanTalonSRX jarg1_, int jarg2, long jarg3);

    @objid ("36ad03f2-6cc6-4dbe-a9d6-848bd0a59ca7")
    public static final native long CanTalonSRX_GetParamResponseInt32(long jarg1, CanTalonSRX jarg1_, int jarg2, long jarg3);

    @objid ("5181b4c8-4b58-4b87-8099-624bde63afa9")
    public static final native long CanTalonSRX_SetPgain(long jarg1, CanTalonSRX jarg1_, long jarg2, double jarg3);

    @objid ("5e952764-2f16-4c9a-841c-8c203fa9057c")
    public static final native long CanTalonSRX_SetIgain(long jarg1, CanTalonSRX jarg1_, long jarg2, double jarg3);

    @objid ("053fb2af-8dac-4e8d-b922-879ceefca05a")
    public static final native long CanTalonSRX_SetDgain(long jarg1, CanTalonSRX jarg1_, long jarg2, double jarg3);

    @objid ("cd87103e-addd-4abb-a50e-ebb8a7e53355")
    public static final native long CanTalonSRX_SetFgain(long jarg1, CanTalonSRX jarg1_, long jarg2, double jarg3);

    @objid ("d1abb2d6-da2d-459a-a057-c06381714e01")
    public static final native long CanTalonSRX_SetIzone(long jarg1, CanTalonSRX jarg1_, long jarg2, int jarg3);

    @objid ("d1b56d10-4ecf-493b-bda9-c27932e98e79")
    public static final native long CanTalonSRX_SetCloseLoopRampRate(long jarg1, CanTalonSRX jarg1_, long jarg2, int jarg3);

    @objid ("71b05854-1f28-4b92-8262-39cbd561b2f4")
    public static final native long CanTalonSRX_SetSensorPosition(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("8bf86926-a577-4338-8971-5793af45cfa9")
    public static final native long CanTalonSRX_SetForwardSoftLimit(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("3a88bda9-32ea-4bd2-86eb-11e433d1b02c")
    public static final native long CanTalonSRX_SetReverseSoftLimit(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("0d440e8b-b8d6-4fc6-a851-2540d3b718eb")
    public static final native long CanTalonSRX_SetForwardSoftEnable(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("991b8445-faf5-42bf-aa08-25f5a8e3198f")
    public static final native long CanTalonSRX_SetReverseSoftEnable(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("7b824970-8a91-42b6-ac25-0368173fdd54")
    public static final native long CanTalonSRX_GetPgain(long jarg1, CanTalonSRX jarg1_, long jarg2, long jarg3);

    @objid ("df4e2b2f-a235-4fdf-9e83-9da73b959b22")
    public static final native long CanTalonSRX_GetIgain(long jarg1, CanTalonSRX jarg1_, long jarg2, long jarg3);

    @objid ("f78cdf9c-2dfa-4ebf-b310-89b72a7ce1bd")
    public static final native long CanTalonSRX_GetDgain(long jarg1, CanTalonSRX jarg1_, long jarg2, long jarg3);

    @objid ("bc2b3a0c-3e5f-4312-96a3-a277dcc18649")
    public static final native long CanTalonSRX_GetFgain(long jarg1, CanTalonSRX jarg1_, long jarg2, long jarg3);

    @objid ("84aed967-f60a-42b1-a3ea-1ce03b339ee8")
    public static final native long CanTalonSRX_GetIzone(long jarg1, CanTalonSRX jarg1_, long jarg2, long jarg3);

    @objid ("18794cc1-ccd8-4a48-99e7-61834e8734ee")
    public static final native long CanTalonSRX_GetCloseLoopRampRate(long jarg1, CanTalonSRX jarg1_, long jarg2, long jarg3);

    @objid ("16b24e21-3cba-47a1-a462-d271dd5e0026")
    public static final native long CanTalonSRX_GetForwardSoftLimit(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("e227ffd1-74e3-45d1-8b8f-12fd00cdc192")
    public static final native long CanTalonSRX_GetReverseSoftLimit(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("f9e3d893-1c51-40e5-8a17-51c7fbf6fda7")
    public static final native long CanTalonSRX_GetForwardSoftEnable(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("9664dde9-23ba-41a6-8042-dc2c84e29edb")
    public static final native long CanTalonSRX_GetReverseSoftEnable(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("0b03a6ff-7a9e-4b08-8f2d-fda68e9e83d1")
    public static final native long CanTalonSRX_SetStatusFrameRate(long jarg1, CanTalonSRX jarg1_, long jarg2, long jarg3);

    @objid ("cdf5464d-3738-4972-9706-556c4e503b10")
    public static final native long CanTalonSRX_ClearStickyFaults(long jarg1, CanTalonSRX jarg1_);

    @objid ("b6d631f5-8fca-447c-9781-a1d2e590fd6a")
    public static final native long CanTalonSRX_GetFault_OverTemp(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("f37f778e-e63f-4195-b74a-219357109ebe")
    public static final native long CanTalonSRX_GetFault_UnderVoltage(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("4654bf98-c3e8-4f64-88c0-e9fde7f9c3ac")
    public static final native long CanTalonSRX_GetFault_ForLim(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("508959d9-32d0-4e95-bb4a-8ae5a699aff0")
    public static final native long CanTalonSRX_GetFault_RevLim(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("086143cf-a0b4-4f14-9456-0753a3a767b8")
    public static final native long CanTalonSRX_GetFault_HardwareFailure(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("dad7bf6f-3406-49dd-886c-55d3424fd28f")
    public static final native long CanTalonSRX_GetFault_ForSoftLim(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("af1eb589-d7e6-4006-9052-d945c075ab95")
    public static final native long CanTalonSRX_GetFault_RevSoftLim(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("4037ad8c-040f-4402-adc6-a8e37986655d")
    public static final native long CanTalonSRX_GetStckyFault_OverTemp(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("4bee049f-adfd-4837-b80b-5c4d4e6aac7b")
    public static final native long CanTalonSRX_GetStckyFault_UnderVoltage(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("506adbe7-9b08-4772-89e2-a4fc332c5bdd")
    public static final native long CanTalonSRX_GetStckyFault_ForLim(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("1e1f649d-d703-4ff1-b7f8-4c9b2fddac98")
    public static final native long CanTalonSRX_GetStckyFault_RevLim(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("87d08f75-a8a0-4e58-8d7a-b7ec20915af7")
    public static final native long CanTalonSRX_GetStckyFault_ForSoftLim(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("1461ffc2-2d29-4625-88f7-0b0f3f799aec")
    public static final native long CanTalonSRX_GetStckyFault_RevSoftLim(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("bcafa89b-9c0d-44d3-92bc-3c031fd35500")
    public static final native long CanTalonSRX_GetAppliedThrottle(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("28b7231b-f07e-4272-b478-8e90163ee6bd")
    public static final native long CanTalonSRX_GetCloseLoopErr(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("4adddb7c-0010-49c6-b6ed-97e6d1c48f87")
    public static final native long CanTalonSRX_GetFeedbackDeviceSelect(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("0b709bfc-c3e0-4835-a447-6ff5af035eda")
    public static final native long CanTalonSRX_GetModeSelect(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("3ac904a0-5d66-4bce-bd51-59295b52bee6")
    public static final native long CanTalonSRX_GetLimitSwitchEn(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("003234ab-91dc-496c-a291-0d86e99abae0")
    public static final native long CanTalonSRX_GetLimitSwitchClosedFor(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("4933d711-6050-4504-804f-dcecf4381dce")
    public static final native long CanTalonSRX_GetLimitSwitchClosedRev(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("d9eb213e-5b2e-4091-9fd1-38306cf32563")
    public static final native long CanTalonSRX_GetSensorPosition(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("b29b349d-c2d2-4768-ac27-06de976e5e9e")
    public static final native long CanTalonSRX_GetSensorVelocity(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("2c8de59a-45b8-4ee3-9e60-74594529b20f")
    public static final native long CanTalonSRX_GetCurrent(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("21ecc0a4-3087-4247-9e07-3e29d857a684")
    public static final native long CanTalonSRX_GetBrakeIsEnabled(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("8f6013db-1b09-490b-8339-3a0e7bef069b")
    public static final native long CanTalonSRX_GetEncPosition(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("d6adcf92-a8f8-41ee-9e63-b0e2adfb2701")
    public static final native long CanTalonSRX_GetEncVel(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("b26c9b24-f119-4d9b-a327-0b47c7958344")
    public static final native long CanTalonSRX_GetEncIndexRiseEvents(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("0720e960-abab-440b-abaf-667e06978a98")
    public static final native long CanTalonSRX_GetQuadApin(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("4e2722c2-1a25-4664-9518-b6ff8fb2265b")
    public static final native long CanTalonSRX_GetQuadBpin(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("cf079fa0-5214-4dd2-a93b-aa618d9a2f02")
    public static final native long CanTalonSRX_GetQuadIdxpin(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("443f83c9-8b5f-4423-ac43-b68fdb92c901")
    public static final native long CanTalonSRX_GetAnalogInWithOv(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("d4184e46-dfc7-4289-90ca-ee0dc85c52ec")
    public static final native long CanTalonSRX_GetAnalogInVel(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("b156114e-5ac6-4f9a-a9d4-5d3ebad6f136")
    public static final native long CanTalonSRX_GetTemp(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("4830c59e-6187-48d1-ae62-2d0bb9b90d5a")
    public static final native long CanTalonSRX_GetBatteryV(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("22e336e3-39a1-4dd5-a5b6-df514bbe5edf")
    public static final native long CanTalonSRX_GetResetCount(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("673ffefd-c78f-4824-b002-b8f0da07af91")
    public static final native long CanTalonSRX_GetResetFlags(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("e112d619-5c4e-4c5e-ad7b-85f18324cd1e")
    public static final native long CanTalonSRX_GetFirmVers(long jarg1, CanTalonSRX jarg1_, long jarg2);

    @objid ("a8836165-61a3-4408-a857-741cfa693d54")
    public static final native long CanTalonSRX_SetDemand(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("65abf132-5cb8-4139-9b35-4de0a51abefc")
    public static final native long CanTalonSRX_SetOverrideLimitSwitchEn(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("752c0195-ad60-4fd4-a3e5-edfe0aa35ece")
    public static final native long CanTalonSRX_SetFeedbackDeviceSelect(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("926f6112-9496-4731-bafe-68af99550fd9")
    public static final native long CanTalonSRX_SetRevMotDuringCloseLoopEn(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("8b837ee5-93e4-40b1-aa78-dbb20046cc0c")
    public static final native long CanTalonSRX_SetOverrideBrakeType(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("400e95ca-0a4c-426d-8513-bb115257dc8f")
    public static final native long CanTalonSRX_SetModeSelect(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("24a9bf42-12eb-48cb-bd15-505caa663636")
    public static final native long CanTalonSRX_SetProfileSlotSelect(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("2e05d2ce-b8fe-429e-a4e2-9bcda640ecf4")
    public static final native long CanTalonSRX_SetRampThrottle(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("88f87b47-7ba7-4577-93fa-9773ee6f8456")
    public static final native long CanTalonSRX_SetRevFeedbackSensor(long jarg1, CanTalonSRX jarg1_, int jarg2);

    @objid ("67523747-e3a6-40e5-b5d0-5fe96114e695")
    public static final native long CanTalonSRX_SWIGUpcast(long jarg1);

}
