/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("ad8d11d7-03be-4e90-8de1-7b160ad80903")
public class CtreCanNode {
    @objid ("28ba240f-2cbf-4ff5-a603-7f1471d96fb7")
    private long swigCPtr;

    @objid ("c5717994-c5fe-4295-9647-201b439394be")
    protected boolean swigCMemOwn;

    @objid ("488cc928-dd7b-46f0-b683-00122c32b235")
    protected CtreCanNode(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    @objid ("e3d1dc7d-b053-4330-84f6-3e8536c66be9")
    protected static long getCPtr(CtreCanNode obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    @objid ("e8f5ea86-9ddb-429c-a21d-cc9742a84b51")
    protected void finalize() {
        delete();
    }

    @objid ("d0ced437-8250-471f-846e-d79191b0adeb")
    public synchronized void delete() {
        if (swigCPtr != 0) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            CanTalonJNI.delete_CtreCanNode(swigCPtr);
          }
          swigCPtr = 0;
        }
    }

    @objid ("3b834e4e-eb80-4e7b-9566-341c8305ebc6")
    public CtreCanNode(SWIGTYPE_p_UINT8 deviceNumber) {
        this(CanTalonJNI.new_CtreCanNode(SWIGTYPE_p_UINT8.getCPtr(deviceNumber)), true);
    }

    @objid ("ef394a0e-0b74-4cba-a779-264701215a57")
    public SWIGTYPE_p_UINT8 GetDeviceNumber() {
        return new SWIGTYPE_p_UINT8(CanTalonJNI.CtreCanNode_GetDeviceNumber(swigCPtr, this), true);
    }

}
