/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("7dfe75d1-e477-4803-998d-9483a080f8de")
public class SWIGTYPE_p_int32_t {
    @objid ("59f5ea1e-6ad6-4432-97ed-11633368f607")
    private long swigCPtr;

    @objid ("18d87d38-72ee-4d1e-a1aa-4a369f28b664")
    public SWIGTYPE_p_int32_t(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }

    @objid ("6f069e23-c8a6-46da-9655-70cb0d390811")
    public SWIGTYPE_p_int32_t() {
        swigCPtr = 0;
    }

    @objid ("b9c74adf-dd3e-4d6e-a1b4-b01cd2a04a17")
    public static long getCPtr(SWIGTYPE_p_int32_t obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

}
