/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("5387e8ba-bf21-4109-b447-21c39da82db4")
public class SWIGTYPE_p_UINT8 {
    @objid ("b7dc60b7-68f8-42bc-90c0-97c99d578537")
    private long swigCPtr;

    @objid ("97907297-1319-40a3-ad90-3527d786731b")
    public SWIGTYPE_p_UINT8(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }

    @objid ("32f66be2-c9f6-4053-92dc-5046742f780f")
    public SWIGTYPE_p_UINT8() {
        swigCPtr = 0;
    }

    @objid ("a4c1bb7d-3ee1-44d5-97ac-e8787c4198a4")
    public static long getCPtr(SWIGTYPE_p_UINT8 obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

}
