/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("c445e517-ca3a-40bf-be7f-619ff62c4b17")
public class SWIGTYPE_p_int {
    @objid ("26747c76-4bfa-4e43-8a84-e094a3f07511")
    private long swigCPtr;

    @objid ("8bc754ac-c9b2-4f1a-8688-f2b714124fbd")
    public SWIGTYPE_p_int(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }

    @objid ("777a64d8-4c24-4bdd-8f4b-bf14ac20a9a5")
    public SWIGTYPE_p_int() {
        swigCPtr = 0;
    }

    @objid ("2eb7f7be-80c7-4d57-a0c6-e2f3734c59c0")
    public static long getCPtr(SWIGTYPE_p_int obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

}
