/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("2f27a857-cb0d-4c7a-9bbe-e21b69d758b1")
public class SWIGTYPE_p_double {
    @objid ("e4c6064d-46e7-4db4-a2e5-e08349b769db")
    private long swigCPtr;

    @objid ("6d30321f-1547-4bb0-b82d-360ad9f0e241")
    public SWIGTYPE_p_double(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }

    @objid ("08740065-8fc9-4e7b-b578-1dd340f3dc31")
    public SWIGTYPE_p_double() {
        swigCPtr = 0;
    }

    @objid ("97cf79dc-470b-4d26-8ffd-31907258704f")
    public static long getCPtr(SWIGTYPE_p_double obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

}
