/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("70d7d835-a74e-46df-80a4-2ab56beb0868")
public class SWIGTYPE_p_CTR_Code {
    @objid ("623ce0e8-507a-4ee0-8690-da4c026dd41a")
    private long swigCPtr;

    @objid ("bdc85f55-c3d3-4e03-bf08-6a8cf879240b")
    public SWIGTYPE_p_CTR_Code(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }

    @objid ("472a5675-0295-42e5-9d68-21f345041802")
    public SWIGTYPE_p_CTR_Code() {
        swigCPtr = 0;
    }

    @objid ("7c7a1062-69e5-4442-89ae-247f2041ba39")
    public static long getCPtr(SWIGTYPE_p_CTR_Code obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

}
