/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("a5546c79-9457-4fd0-b12d-c26fcc5d3e6d")
public class SWIGTYPE_p_uint8_t {
    @objid ("9ecd2f29-8c46-4943-8f17-7f4a8bc15ddc")
    private long swigCPtr;

    @objid ("cfc0b3d0-4a1a-44a6-b139-c5d1ca3f0cc3")
    public SWIGTYPE_p_uint8_t(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }

    @objid ("86c5d03c-21f4-49eb-b5c6-d69292ef1051")
    public SWIGTYPE_p_uint8_t() {
        swigCPtr = 0;
    }

    @objid ("ea9690f0-1ca1-4711-b05f-26d9f571241f")
    public static long getCPtr(SWIGTYPE_p_uint8_t obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

}
