/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("8981ac91-2784-492d-b5ed-209612f762b1")
public class SWIGTYPE_p_float {
    @objid ("5c3dda54-10f9-4eb0-9465-f20279939e61")
    private long swigCPtr;

    @objid ("fd713059-b2c8-4e75-8d46-ee9c9b5ac30f")
    public SWIGTYPE_p_float(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }

    @objid ("e5316339-ffa9-4660-a722-ccf1e414706f")
    public SWIGTYPE_p_float() {
        swigCPtr = 0;
    }

    @objid ("231abffb-608d-476b-940d-c638a1ef9866")
    public static long getCPtr(SWIGTYPE_p_float obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

}
