/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package edu.wpi.first.wpilibj.hal;

import com.modeliosoft.modelio.javadesigner.annotations.objid;

@objid ("e629bd6a-1269-40cd-9db5-cb1af3b92d51")
public class SWIGTYPE_p_uint32_t {
    @objid ("88c46e8d-79bd-4143-b13a-aa86d15269b3")
    private long swigCPtr;

    @objid ("1a7c9896-3626-4a06-af48-094fbe018de3")
    public SWIGTYPE_p_uint32_t(long cPtr, boolean futureUse) {
        swigCPtr = cPtr;
    }

    @objid ("76e1354a-3fc9-4c68-a9ce-d118738ecea3")
    public SWIGTYPE_p_uint32_t() {
        swigCPtr = 0;
    }

    @objid ("f2cea987-2760-4302-b791-b616d502cd42")
    public static long getCPtr(SWIGTYPE_p_uint32_t obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

}
