package edu.wpi.first.wpilibj.can;

import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import edu.wpi.first.wpilibj.hal.JNIWrapper;

/**
 * JNA Wrapper for library <b>CAN</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@objid ("78e952d0-84a2-4250-8d86-8930580031f3")
public class CANJNI extends JNIWrapper {
    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("6868fa39-e8b5-4939-9877-0545ed10dd82")
    public static final int LM_STATUS_LIMIT_REV = 0x02;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("576c741d-a691-4155-b267-93a2b4166fb9")
    public static final int LM_API_CFG_MAX_VOUT = ((0x00020000 | 0x02000000 | 0x00001c00) | (7 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("243cdc74-3988-4de5-ab7d-4446749f8cac")
    public static final int LM_PSTAT_CANERR_B0 = 30;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("b192acff-79ec-4516-ac47-9a506c54c04a")
    public static final int LM_API_SPD_DIS = ((0x00020000 | 0x02000000 | 0x00000400) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("0c9c818e-634b-47b6-92c8-0d4a66317e3c")
    public static final int CAN_MSGID_DTYPE_ACCEL = 0x05000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("7ce2cab4-7dc4-47e7-84e7-945e092bdfb8")
    public static final int LM_API_STATUS_FAULT = ((0x00020000 | 0x02000000 | 0x00001400) | (7 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("f1d61986-2384-44e4-beac-cc200faf6590")
    public static final int CAN_MSGID_API_FIRMVER = 0x00000200;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("bb56520f-828b-4b9e-b0b2-4221f456aea1")
    public static final int LM_API_ICTRL_EN = ((0x00020000 | 0x02000000 | 0x00001000) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("57d23b11-75da-41e4-8875-c858adf69163")
    public static final int CAN_MSGID_API_ENUMERATE = 0x00000240;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("76f78982-83eb-4e22-9050-66a49641c617")
    public static final int LM_API_SPD_EN = ((0x00020000 | 0x02000000 | 0x00000400) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("7e93ddb3-69c6-486a-b974-95cf8a6a4e40")
    public static final int LM_API_CFG_LIMIT_REV = ((0x00020000 | 0x02000000 | 0x00001c00) | (6 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("4e97236d-6d6d-49ad-a900-2bd94dafd0cc")
    public static final int LM_PSTAT_POS_B2 = 11;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("2fb19386-d48e-4f5b-a47e-095b587a904e")
    public static final int LM_PSTAT_POS_B3 = 12;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("1041d847-740e-4f86-900e-03e3c9f0f585")
    public static final int LM_API_VCOMP_EN = ((0x00020000 | 0x02000000 | 0x00000800) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("cd1caa67-a1c7-41f4-ab99-5d98191345fe")
    public static final int LM_PSTAT_POS_B0 = 9;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5420175d-8a99-4bdc-8ffa-7487486f656a")
    public static final int LM_PSTAT_POS_B1 = 10;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("7d02b16f-5e6f-4cb4-954d-8ae7351a7b22")
    public static final int LM_API_HWVER = ((0x00020000 | 0x1f000000) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("df1963bb-e24e-4b04-a2ff-5bbff16dacce")
    public static final int LM_STATUS_FAULT_ILIMIT = 0x01;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("02aa55fa-cbd1-4de6-ab8a-31d7f31edb05")
    public static final int LM_API_ICTRL_DC = ((0x00020000 | 0x02000000 | 0x00001000) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("4c4550d7-e674-4e81-a674-78d398d978bd")
    public static final int LM_API_VOLT = (0x00020000 | 0x02000000 | 0x00000000);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("b242cb47-f71c-46fa-986c-b3a0ac7faa67")
    public static final int CAN_API_MC_VCOMP = 0x00000800;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d997e91f-acc0-4cbe-a69e-0b2b74128c1a")
    public static final int LM_PSTAT_END = 0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("a306d174-5475-42ce-8564-d92f949e3666")
    public static final int LM_API_CFG_LIMIT_FWD = ((0x00020000 | 0x02000000 | 0x00001c00) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5e1734b0-ed5c-4493-be21-98d0d8fb6c14")
    public static final int CAN_MSGID_DTYPE_M = 0x1f000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e6642ead-f46c-4838-949e-d7108fa0d82c")
    public static final int CAN_API_MC_ICTRL = 0x00001000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e9198df2-37d3-468e-8098-d72d1002480d")
    public static final int CAN_API_MC_CFG = 0x00001c00;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("1cb07705-5cdf-466b-b9df-896d06e3f564")
    public static final int CAN_MSGID_MFR_DEKA = 0x00030000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("2d59ce33-bc26-4029-89da-63add44e7c2b")
    public static final int CAN_MSGID_API_SYSRST = 0x00000040;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("1f52ae5d-1560-4d88-b3a1-2406f2bc22d4")
    public static final int LM_REF_QUAD_ENCODER = 0x03;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5df60141-bd0b-44e3-92d9-563e4fc3bffd")
    public static final int LM_API_SYNC_PEND_NOW = 0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("227d0feb-2cd8-4f4a-9a15-877df63cc174")
    public static final int LM_STATUS_CMODE_CURRENT = 0x01;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("b06b4f41-d5a5-4c37-a6ed-3a8025d723e7")
    public static final int LM_API_STATUS_TEMP = ((0x00020000 | 0x02000000 | 0x00001400) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("380c5ff6-6d11-4b12-8431-99716a866509")
    public static final int LM_API_SPD_DC = ((0x00020000 | 0x02000000 | 0x00000400) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("df7da7f3-5145-4866-863d-80f35b32531d")
    public static final int CAN_API_MC_POS = 0x00000c00;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("03aa92a2-053c-4bf9-bc01-4ceba2881a3d")
    public static final int LM_STATUS_LIMIT_SFWD = 0x04;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("0a3e3cf7-24fb-4c82-bf81-94c775c8e3ec")
    public static final int LM_API_ICTRL_DIS = ((0x00020000 | 0x02000000 | 0x00001000) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("71bd14bb-bdf5-452d-bfae-0605eeaa4cae")
    public static final int LM_API_VOLT_SET = ((0x00020000 | 0x02000000 | 0x00000000) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("042afd31-3976-4133-9a9c-0b602140533d")
    public static final int CAN_MSGID_API_HEARTBEAT = 0x00000140;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("cc5f1481-03dd-4ebf-8df2-5dd093140030")
    public static final int LM_FAULT_CURRENT = 0x01;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("a6cbdfe0-6858-4c15-a93a-7fb5c1fcaa63")
    public static final int CAN_MSGID_DTYPE_GYRO = 0x04000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("788f4df2-0521-4b74-a1e0-a2dcbcbb233b")
    public static final int LM_STATUS_FAULT_TLIMIT = 0x02;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("cb92689c-ea2b-4dd4-8667-e275880bdfeb")
    public static final int CAN_MSGID_MFR_S = 16;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("68c4b895-91f9-46e0-8581-24596ad7980a")
    public static final int LM_API_SPD_T_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00000400) | (10 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d6d03268-cdee-43dd-bdba-ab461facfacc")
    public static final int CAN_MSGID_MFR_M = 0x00ff0000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("f95ef6e2-2dca-4b9c-b08d-55becf7a72dd")
    public static final int LM_STATUS_CMODE_POS = 0x03;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5202c4cd-3c8d-4d81-8b3e-e27648048389")
    public static final int LM_REF_POT = 0x01;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("1ebac964-cc11-4b31-bc32-60c7aca39ed9")
    public static final int LM_HWVER_UNKNOWN = 0x00;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("470c9076-9d71-4dce-9942-261b7ea98b1f")
    public static final int LM_API_CFG_BRAKE_COAST = ((0x00020000 | 0x02000000 | 0x00001c00) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5004a723-f1a6-4404-a5a3-03a6a6962d5c")
    public static final int LM_HWVER_JAG_1_0 = 0x01;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("72fa5160-cd6b-4f3e-93fa-5202416d19db")
    public static final int CAN_MSGID_DEVNO_BCAST = 0x00000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("eab1f434-d0bd-43ba-8722-d1693f93bb17")
    public static final int LM_API_VOLT_T_SET = ((0x00020000 | 0x02000000 | 0x00000000) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("cc1fb82d-d1b0-4fa7-9f0d-a714cba4167f")
    public static final int LM_STATUS_LIMIT_STKY_SREV = 0x80;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("98127292-53d2-40e2-8aec-03ece5ed1ebe")
    public static final int LM_API_ICTRL_IC = ((0x00020000 | 0x02000000 | 0x00001000) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("fa892b05-6ec4-4ec3-84fd-7b6a0fe1b1f6")
    public static final int LM_FAULT_COMM = 0x10;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("4e3ee88f-f8e0-47fc-8a5e-4440232f9356")
    public static final int LM_API_ICTRL_T_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00001000) | (9 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("b5f31e15-a9bb-492a-857c-88f21d9b9917")
    public static final int LM_PSTAT_SPD_B2 = 15;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("f5bc6856-712c-43f1-bb90-ffc677930b6a")
    public static final int LM_PSTAT_SPD_B1 = 14;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("0fb6009b-53d6-4f18-b658-1aed55cd533f")
    public static final int LM_PSTAT_STKY_FLT_CLR = 21;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("fb61cae1-f06e-455e-ba74-b325746c94a4")
    public static final int LM_PSTAT_SPD_B3 = 16;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("0052f9de-b0f2-4ec5-b714-0b0918b51b21")
    public static final int CAN_STATUS_MFG_S = 16;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("bcef3ae3-8f24-4a8d-aa9c-10101b5e17d2")
    public static final int LM_API_SPD_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00000400) | (11 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d09e8fc7-6391-4663-879f-14f94e7c3aa2")
    public static final int LM_API_STATUS_LIMIT = ((0x00020000 | 0x02000000 | 0x00001400) | (6 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("da204439-7824-487c-a969-ce8d0de44b23")
    public static final int LM_API_VOLT_EN = ((0x00020000 | 0x02000000 | 0x00000000) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("79968c82-d317-4d46-8a7c-41621ca6eb52")
    public static final int LM_API_VOLT_RAMP_DIS = 0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("2e5becd3-4a8c-4f38-862b-d92d09208623")
    public static final int LM_PSTAT_TEMP_B0 = 7;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("7ff8287d-7863-40f9-ae24-9dc4801c64d2")
    public static final int LM_PSTAT_TEMP_B1 = 8;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("2731355a-2fbb-44f4-ab14-84263629f097")
    public static final int LM_API_POS_IC = ((0x00020000 | 0x02000000 | 0x00000c00) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("2d77b861-6b4a-466e-85e3-ddd42e142bc0")
    public static final int CAN_MSGID_DTYPE_MOTOR = 0x02000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("c42d0c83-7dae-445e-9406-a467e39b855a")
    public static final int LM_API_SPD_T_EN = ((0x00020000 | 0x02000000 | 0x00000400) | (7 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("73bf9231-f69a-4d3f-bdd1-63a6c4ecce94")
    public static final int CAN_MSGID_DEVNO_M = 0x0000003f;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("a6a50469-cee1-4448-8fba-1d925fb0c2ed")
    public static final int LM_PSTAT_VOLTBUS_B1 = 4;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("ed9b700e-9b9b-488f-b18f-0f98cd3ce35b")
    public static final int LM_API_UPD_PING = ((0x00020000 | 0x1f000000) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("fef5b8ab-1ac7-4e8d-939b-ce7aecab4edc")
    public static final int LM_API_POS_T_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00000c00) | (10 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("878bdfe5-5bb1-4d64-81f9-e15bb6594940")
    public static final int CAN_MSGID_DEVNO_S = 0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("738ea32e-b76f-4583-83e2-bcbcccf3734f")
    public static final int LM_API_TRUST_HEARTBEAT = ((0x00020000 | 0x1f000000) | (13 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9b4b15fb-5ecf-4804-8989-02541de7ab59")
    public static final int LM_PSTAT_VOLTBUS_B0 = 3;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("c4c3f74e-21a4-4a35-8d08-b6b2d90b9d85")
    public static final int LM_PSTAT_SPD_B0 = 13;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("3d34479e-075a-4f2c-a806-be463a9410d9")
    public static final int LM_API_CFG = (0x00020000 | 0x02000000 | 0x00001c00);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("27dc3711-7710-45ff-9ca8-0e8c81973e02")
    public static final int LM_PSTAT_FLT_COUNT_COMM = 28;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("6462781d-eda4-4143-a92c-9473f7c20c07")
    public static final int CAN_MSGID_API_SYSHALT = 0x00000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("fad6a1fd-3e9f-4459-9f59-205385601437")
    public static final int LM_API_UPD_DOWNLOAD = ((0x00020000 | 0x1f000000) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("56314a66-347e-455b-b660-80d72764bc29")
    public static final int LM_API_STATUS_CMODE = ((0x00020000 | 0x02000000 | 0x00001400) | (9 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("caba639d-0f5d-4c3e-aef7-e6b0d3ef5ea9")
    public static final int LM_API_VCOMP_IN_RAMP = ((0x00020000 | 0x02000000 | 0x00000800) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("68b7f568-c97a-495e-9c99-3f52681cc061")
    public static final int LM_STATUS_FAULT_VLIMIT = 0x04;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("6f336529-5e9c-43b5-ad0f-6d073677e81b")
    public static final int LM_STATUS_LIMIT_SREV = 0x08;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("512af03b-255b-4718-8d6c-6b11db4c83a7")
    public static final int CAN_MSGID_DTYPE_S = 24;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("4bee81d7-9829-4f9d-850d-917a9ce06c97")
    public static final int LM_PSTAT_FLT_COUNT_VOLTBUS = 26;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("3245ad62-dd4d-4b29-b47e-f456b320cf47")
    public static final int CAN_API_MC_STATUS = 0x00001400;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("795e47e8-874a-409b-9154-d48763c065e7")
    public static final int LM_API_VOLT_T_EN = ((0x00020000 | 0x02000000 | 0x00000000) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("232d2d2a-65f1-4e19-8ea3-15478efe1606")
    public static final int LM_API_STATUS_VOLTBUS = ((0x00020000 | 0x02000000 | 0x00001400) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("72cd2290-a49f-43f2-b4ca-2e44f0417862")
    public static final int LM_API_UPD = (0x00020000 | 0x1f000000);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9b94ffb6-2ef1-4def-82a4-0c9344fd326a")
    public static final int LM_API_UPD_REQUEST = ((0x00020000 | 0x1f000000) | (6 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("1d193cde-6c3b-4c5b-b4ae-657f12fd4c73")
    public static final int CAN_API_MC_VOLTAGE = 0x00000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e15c5a87-21be-484a-899f-25348ee35533")
    public static final int LM_API_PSTAT_PER_EN_S3 = ((0x00020000 | 0x02000000 | 0x00001800) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("aca2b18a-cd72-4570-8443-59cb992fc15a")
    public static final int LM_API_PSTAT_PER_EN_S2 = ((0x00020000 | 0x02000000 | 0x00001800) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("fa6181d4-1b88-43a2-9f53-a982d9d0aeca")
    public static final int CAN_API_MC_PSTAT = 0x00001800;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9dd82da8-54e4-4de0-a658-944c41825a39")
    public static final int LM_PSTAT_CANERR_B1 = 31;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("351d3e9a-4fa4-4179-9d85-1ffcbb30ee87")
    public static final int LM_API_PSTAT_PER_EN_S1 = ((0x00020000 | 0x02000000 | 0x00001800) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("a170d4b4-7db0-4ad1-aa89-d6bcbf4644c6")
    public static final int LM_REF_ENCODER = 0x00;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("846df290-246c-4d91-9a1e-f89cfca15fa2")
    public static final int LM_API_PSTAT_PER_EN_S0 = ((0x00020000 | 0x02000000 | 0x00001800) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("07c7d15a-b323-468e-a52d-13074d04dbe1")
    public static final int LM_API_STATUS_CURRENT = ((0x00020000 | 0x02000000 | 0x00001400) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5a73e952-d377-4a8a-bea1-ea14366b3836")
    public static final int LM_API_POS_SET = ((0x00020000 | 0x02000000 | 0x00000c00) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("f2bbf169-4d2c-4f02-a8bc-eefad62ec810")
    public static final int LM_STATUS_LIMIT_STKY_FWD = 0x10;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("bd83826e-7522-4f99-bc9f-e445fecb4a47")
    public static final int LM_API_ICTRL = (0x00020000 | 0x02000000 | 0x00001000);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("61369dc3-c8da-4e0d-910a-19d454986e8c")
    public static final int LM_HWVER_JAG_2_0 = 0x02;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("16d23b55-fe04-4428-83f4-56f00324472d")
    public static final int CAN_STATUS_MFG_M = 0x00ff0000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("78dc32c8-a298-40b9-ad1d-c86c0c527431")
    public static final int LM_PSTAT_LIMIT_CLR = 18;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d05773cc-7628-4778-95e7-8bd095423e39")
    public static final int LM_API_CFG_POT_TURNS = ((0x00020000 | 0x02000000 | 0x00001c00) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("8d375efc-9b34-4ce1-8f50-1e78f7019191")
    public static final int LM_API_POS_REF = ((0x00020000 | 0x02000000 | 0x00000c00) | (6 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("97816a14-8c34-4d9e-a971-7daf9042c10a")
    public static final int LM_API_SPD_PC = ((0x00020000 | 0x02000000 | 0x00000400) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("b0724e07-b649-4426-ac4c-ff897e850ff1")
    public static final int LM_API_STATUS_VOUT = ((0x00020000 | 0x02000000 | 0x00001400) | (10 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d0be18ab-9565-4839-8c76-c6020167d330")
    public static final int CAN_MSGID_API_SYSRESUME = 0x00000280;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("a15d7794-21d7-42a2-91b3-ac22499cad32")
    public static final int LM_API_UNTRUST_EN = ((0x00020000 | 0x1f000000) | (11 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("8b6cafdb-bab9-497b-88fd-bb0481d5af48")
    public static final int LM_PSTAT_CANSTS = 29;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("cf4c1713-57c6-4042-a2ba-f0d9d92fcde0")
    public static final int LM_API_POS_DC = ((0x00020000 | 0x02000000 | 0x00000c00) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("8ade63b9-1547-4bc9-b749-59eab5f2bc6c")
    public static final int LM_API_STATUS_POS = ((0x00020000 | 0x02000000 | 0x00001400) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("78c4a32d-5ce8-4489-83bc-3475e17e3a58")
    public static final int LM_API_SPD_SET = ((0x00020000 | 0x02000000 | 0x00000400) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("6a25f6b6-140d-4227-ba41-2b532b3ca959")
    public static final int CAN_MSGID_FULL_M = 0x1fffffff;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("cab763d8-74f9-49dd-8ba3-2f362e572848")
    public static final int LM_API_STATUS_SPD = ((0x00020000 | 0x02000000 | 0x00001400) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9b8db317-6207-4cff-8e1e-4351030cddcb")
    public static final int LM_PSTAT_STKY_FLT_NCLR = 20;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("34d55d1b-99f4-48d5-a358-5f4ab32293e8")
    public static final int LM_API_STATUS = (0x00020000 | 0x02000000 | 0x00001400);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("522aaac2-7430-40f2-8b22-f85b31c08ac5")
    public static final int LM_API_TRUST_EN = ((0x00020000 | 0x1f000000) | (12 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e9fe2623-677a-40b1-8b67-437b8459131e")
    public static final int LM_API_ICTRL_T_SET = ((0x00020000 | 0x02000000 | 0x00001000) | (7 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("54a914e1-7eab-40d0-9a1b-55b1984054c9")
    public static final int CAN_STATUS_CODE_M = 0x0000ffff;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5aebd433-38f0-4a88-8bdb-5b17a829a9f8")
    public static final int CAN_STATUS_CODE_S = 0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("55880bf8-2e52-48c4-b9c7-592cc675e006")
    public static final int LM_API_POS_T_EN = ((0x00020000 | 0x02000000 | 0x00000c00) | (7 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e96e6742-f8f1-4fb7-a1d7-30a1b9f468d3")
    public static final int LM_API_PSTAT = (0x00020000 | 0x02000000 | 0x00001800);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9d0b06d5-c3ca-4eda-bbb9-b1e75c1238c3")
    public static final int LM_PSTAT_FAULT = 19;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("f5765127-2706-4719-b81c-4532ffe6452f")
    public static final int LM_PSTAT_FLT_COUNT_GATE = 27;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("68763af2-d9e6-48c9-926b-1eeb12e29d60")
    public static final int LM_API_ICTRL_T_EN = ((0x00020000 | 0x02000000 | 0x00001000) | (6 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5a3445cf-63bb-4707-a8a8-be89e56a2175")
    public static final int CAN_MSGID_API_DEVQUERY = 0x000000c0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9d181701-6faf-4775-9365-1f1665add0d4")
    public static final int CAN_MSGID_DTYPE_USONIC = 0x06000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("89199a3d-a8d8-4c25-8b17-e55abcec3c0f")
    public static final int LM_STATUS_CMODE_VCOMP = 0x04;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9cd9986d-ba3c-4127-a15f-95bad6bfc392")
    public static final int LM_API_SPD_T_SET = ((0x00020000 | 0x02000000 | 0x00000400) | (8 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("01e17530-2666-4f91-8a71-834afb82c16d")
    public static final int LM_API_POS_EN = ((0x00020000 | 0x02000000 | 0x00000c00) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("35f0be43-e3f0-42a3-98d2-19d15a6e5494")
    public static final int LM_API_VOLT_DIS = ((0x00020000 | 0x02000000 | 0x00000000) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("78a6406b-023d-43a4-afcb-c316f63670d7")
    public static final int LM_STATUS_LIMIT_FWD = 0x01;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("89e245f1-23c5-4b4f-a4e0-bc90fdc830f1")
    public static final int LM_API_VCOMP_DIS = ((0x00020000 | 0x02000000 | 0x00000800) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("90a3030e-6613-48f4-8db1-cd8280236cbb")
    public static final int LM_REF_INV_ENCODER = 0x02;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("4d459747-be31-4790-91d0-c0bf25585c56")
    public static final int LM_API_CFG_NUM_BRUSHES = ((0x00020000 | 0x02000000 | 0x00001c00) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("8d83be64-7073-401f-8734-f06e4294b03a")
    public static final int CAN_MSGID_DTYPE_RELAY = 0x03000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("ab143b06-65c2-4a1d-ba2c-2ec6384d1ef6")
    public static final int CAN_MSGID_API_DEVASSIGN = 0x00000080;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("bd8f0621-761e-448f-856e-6f6d2d6d2af3")
    public static final int LM_API_VOLT_T_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00000000) | (7 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("4c5c9d8e-ec98-411e-b370-3709f71f83ce")
    public static final int CAN_API_MC_SPD = 0x00000400;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("860a0412-bd55-4b6c-9748-34b0e38ca463")
    public static final int LM_API_CFG_ENC_LINES = ((0x00020000 | 0x02000000 | 0x00001c00) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("efbf76e4-358e-4f62-b78d-5ba7dc7f1f4a")
    public static final int LM_REF_NONE = 0xff;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("c8a98f61-087a-43c5-bfb5-b4af4cc5ecda")
    public static final int LM_FAULT_VBUS = 0x04;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("28114c2b-2a2f-43ba-89a9-475141d950d2")
    public static final int LM_API_VOLT_SET_RAMP = ((0x00020000 | 0x02000000 | 0x00000000) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("a8491417-bf45-4156-b50d-0d0d7391faea")
    public static final int LM_API_SPD_REF = ((0x00020000 | 0x02000000 | 0x00000400) | (6 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("67138cc8-8db0-4ef8-8357-5d03fc3b5ce3")
    public static final int LM_API_STATUS_POWER = ((0x00020000 | 0x02000000 | 0x00001400) | (8 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("420da3ff-3168-4555-af15-d17595452bb1")
    public static final int LM_PSTAT_VOLTOUT_B1 = 2;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("65a3e830-1d25-47d0-a8c8-ca6b0056a0ec")
    public static final int LM_API_VCOMP_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00000800) | (9 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("bf01fb1a-0933-4af0-a5e8-9fa6c3affe85")
    public static final int LM_PSTAT_VOLTOUT_B0 = 1;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("be6477e8-cfe3-4140-ac35-89eaffdd95bc")
    public static final int LM_API_CFG_LIMIT_MODE = ((0x00020000 | 0x02000000 | 0x00001c00) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("299bcff6-0fab-41d6-91ba-8404dccedadb")
    public static final int LM_PSTAT_VOUT_B1 = 23;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("6a551772-9ca2-4fd2-87ed-1bc1d7aae72c")
    public static final int LM_API_UPD_SEND_DATA = ((0x00020000 | 0x1f000000) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("361b075b-ebe6-4290-85ec-ab70b838c507")
    public static final int LM_PSTAT_FLT_COUNT_CURRENT = 24;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("a5addcca-1416-4c60-be66-7b65799716dd")
    public static final int LM_PSTAT_VOUT_B0 = 22;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d89b01b7-34e9-4b70-a0d6-bc559a36818c")
    public static final int LM_API_PSTAT_CFG_S0 = ((0x00020000 | 0x02000000 | 0x00001800) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9d992d89-5d44-4a3a-b727-3d27f600b16e")
    public static final int LM_PSTAT_LIMIT_NCLR = 17;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9731609e-6d9c-4a3b-9a18-99266fe4fe7c")
    public static final int LM_API_PSTAT_CFG_S1 = ((0x00020000 | 0x02000000 | 0x00001800) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("df00fa17-bc0e-4979-9014-3d215b9b53e7")
    public static final int LM_API_PSTAT_CFG_S2 = ((0x00020000 | 0x02000000 | 0x00001800) | (6 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("3a846371-505c-4f21-acad-93621a0a0a74")
    public static final int LM_API_PSTAT_CFG_S3 = ((0x00020000 | 0x02000000 | 0x00001800) | (7 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5e57200a-8a3a-4ae9-81a8-6eb88bd632dd")
    public static final int LM_API_VCOMP_SET = ((0x00020000 | 0x02000000 | 0x00000800) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("afb5034a-a9eb-4b8c-ab6c-300e498a30c4")
    public static final int CAN_MSGID_API_UPDATE = 0x000001c0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("3d770a6e-0581-4efd-b5c9-f1b337e65f68")
    public static final int LM_API_CFG_FAULT_TIME = ((0x00020000 | 0x02000000 | 0x00001c00) | (8 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("eb0546e3-c139-4159-9476-a89c70eff459")
    public static final int LM_API_STATUS_VOLTOUT = ((0x00020000 | 0x02000000 | 0x00001400) | (0 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("459a9420-db9f-462f-b4ca-a0df51c4ca5c")
    public static final int LM_API_ICTRL_SET = ((0x00020000 | 0x02000000 | 0x00001000) | (2 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("40d49a40-a5ca-44a0-91a1-a3b6a097bc5b")
    public static final int CAN_MSGID_API_M = 0x0000ffc0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("2fc9e067-08dd-4d15-9ef9-05e220c1fcb4")
    public static final int LM_STATUS_CMODE_SPEED = 0x02;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e74bca44-59db-4f07-aef3-50effe6d6ee7")
    public static final int CAN_MSGID_API_CLASS_M = 0x0000fc00;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("c380d13b-5be6-457f-940d-3c316c8d9098")
    public static final int LM_API_PSTAT_DATA_S3 = ((0x00020000 | 0x02000000 | 0x00001800) | (11 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("c87b5421-4025-472c-b4ae-a3089338ad3f")
    public static final int CAN_MSGID_API_S = 6;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("38be689f-3ee3-4f57-93e5-cb36386cd34a")
    public static final int LM_API_STATUS_FLT_COUNT = ((0x00020000 | 0x02000000 | 0x00001400) | (12 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d1875e97-8ff8-435f-a56d-83eb98b84e84")
    public static final int LM_API_PSTAT_DATA_S2 = ((0x00020000 | 0x02000000 | 0x00001800) | (10 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("c598f48e-f9f9-42d0-b8b5-44ccc35e541f")
    public static final int LM_API_PSTAT_DATA_S1 = ((0x00020000 | 0x02000000 | 0x00001800) | (9 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("03e1994a-42c8-4aab-a2cd-498e78b7fd29")
    public static final int LM_API_PSTAT_DATA_S0 = ((0x00020000 | 0x02000000 | 0x00001800) | (8 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("076b8141-2751-4525-9470-bae2f9811b8f")
    public static final int LM_API_ICTRL_PC = ((0x00020000 | 0x02000000 | 0x00001000) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("b842433b-5bd5-4b09-b2a8-a499b26569e2")
    public static final int LM_API_POS_PC = ((0x00020000 | 0x02000000 | 0x00000c00) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("b22174f3-ade6-4756-897b-7f0ffd1922fa")
    public static final int CAN_MSGID_MFR_LM = 0x00020000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("392fdf1c-8ec7-4b86-b574-95d4a14cba7b")
    public static final int LM_API_POS_DIS = ((0x00020000 | 0x02000000 | 0x00000c00) | (1 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("60b917e5-823c-4dd3-b583-711d967d3956")
    public static final int CAN_MSGID_DTYPE_BCAST = 0x00000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("956d68f4-7ec9-4bb8-86a6-ffd6b730187e")
    public static final int LM_STATUS_CMODE_VOLT = 0x00;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("350125fd-4605-4bfe-a920-fcfc883b853a")
    public static final int CAN_STATUS_DTYPE_S = 24;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5f9e1b1a-fd00-4ffe-8e98-1965a6bfdb16")
    public static final int LM_API_POS_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00000c00) | (11 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("60f2efdd-8a80-4f0f-ae42-b20e48bcf325")
    public static final int LM_FAULT_GATE_DRIVE = 0x08;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("b1f7e264-a026-4605-a777-e1aac9c0c967")
    public static final int CAN_STATUS_DTYPE_M = 0x1f000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("3321f6a4-d61f-4bb4-a8b2-ae1a46dd0cce")
    public static final int LM_STATUS_LIMIT_STKY_REV = 0x20;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("ed5a45c1-ed5e-43ab-af68-7e3a2bfee907")
    public static final int CAN_MSGID_DTYPE_ROBOT = 0x01000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("91879ab8-b4df-4efb-b787-5b7ff2f6e76a")
    public static final int CAN_API_MC_ACK = 0x00002000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("50fab891-68b6-4252-9e57-423512269b87")
    public static final int LM_API_VCOMP = (0x00020000 | 0x02000000 | 0x00000800);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("46270bbe-f2ec-40dd-be27-801084c25859")
    public static final int LM_API_UPD_ACK = ((0x00020000 | 0x1f000000) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d1ac3f35-61f0-4cea-8111-9f64cfb1d663")
    public static final int LM_API_VCOMP_COMP_RAMP = ((0x00020000 | 0x02000000 | 0x00000800) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("6b801f8d-9b6c-40b5-9f94-25b1b34a03be")
    public static final int LM_API_VCOMP_T_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00000800) | (8 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("0b170953-b8d8-41c9-affa-c8cd0a73af2d")
    public static final int LM_API_POS = (0x00020000 | 0x02000000 | 0x00000c00);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("f79281c9-e73f-4a74-b923-8f2851d647f7")
    public static final int CAN_MSGID_API_SYNC = 0x00000180;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e963e14d-5fa6-4e67-bc03-5af8e42cb5c7")
    public static final int LM_API_ICTRL_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00001000) | (10 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e9cb5710-0ff9-4ea4-91e5-f22ef7840e75")
    public static final int LM_PSTAT_CURRENT_B1 = 6;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("f8cfcb78-25aa-4f9d-8382-012d6c52f762")
    public static final int LM_API_SPD = (0x00020000 | 0x02000000 | 0x00000400);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("08297eff-712f-45db-8542-c17e7e260497")
    public static final int LM_PSTAT_CURRENT_B0 = 5;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("a12bea9d-702b-4ec5-9746-97f9a76b5e65")
    public static final int CAN_MSGID_DTYPE_UPDATE = 0x1f000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("434e78a4-4f3c-4d89-9a4f-8910281424ec")
    public static final int LM_API_SPD_IC = ((0x00020000 | 0x02000000 | 0x00000400) | (4 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("48ce6545-c61a-4ed7-9c27-54a0f40e3043")
    public static final int LM_API_ACK = (0x00020000 | 0x02000000 | 0x00002000);

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("5e812778-d4e3-4196-99aa-304397104840")
    public static final int LM_FAULT_TEMP = 0x02;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("e505e062-059d-4d14-a094-ea7ff51789ef")
    public static final int LM_API_VCOMP_T_SET = ((0x00020000 | 0x02000000 | 0x00000800) | (6 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("85ae2182-9e81-40eb-9dbd-5097d6fab4bc")
    public static final int LM_PSTAT_FLT_COUNT_TEMP = 25;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("cf449d2f-8d86-4fd7-98d7-622e68b56f71")
    public static final int LM_API_VOLT_SET_NO_ACK = ((0x00020000 | 0x02000000 | 0x00000000) | (8 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("4ccce2f6-922d-4a5d-a411-e3708a5af89d")
    public static final int CAN_MSGID_DTYPE_GEART = 0x07000000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("c6f1554a-b8b6-47c7-86dc-b93f30cbb567")
    public static final int CAN_MSGID_MFR_NI = 0x00010000;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("ad5b01fc-0c34-4118-87ef-e548a2f0ba34")
    public static final int LM_API_POS_T_SET = ((0x00020000 | 0x02000000 | 0x00000c00) | (8 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("808947ff-7a2c-42c8-8c38-ce205986c999")
    public static final int LM_API_STATUS_STKY_FLT = ((0x00020000 | 0x02000000 | 0x00001400) | (11 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("79b2c33c-0be8-4fb6-afc2-882e41d06521")
    public static final int LM_API_UPD_RESET = ((0x00020000 | 0x1f000000) | (3 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("d4da7389-b195-4d9f-a391-9cc232c4d8b6")
    public static final int CAN_MSGID_API_ID_M = 0x000003c0;

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("bb14651c-4515-4d9e-a897-cc10b0bf1407")
    public static final int LM_API_VCOMP_T_EN = ((0x00020000 | 0x02000000 | 0x00000800) | (5 << 6));

    /**
     * <i>native declaration : src\main\include\CAN\can_proto.h</i>
     */
    @objid ("9e5a2ace-233e-44fe-981f-9143e22904c9")
    public static final int LM_STATUS_LIMIT_STKY_SFWD = 0x40;

    @objid ("53e65fec-98bc-499a-97f4-a1f78772a2d4")
    public static final int CAN_SEND_PERIOD_NO_REPEAT = 0;

    @objid ("fe8885b3-089b-4084-a842-fd95d44120f9")
    public static final int CAN_SEND_PERIOD_STOP_REPEATING = -1;

/* Flags in the upper bits of the messageID */
    @objid ("cd446cbb-7658-4c24-8fe0-3bdbbadd8519")
    public static final int CAN_IS_FRAME_REMOTE = 0x80000000;

    @objid ("b8c419ce-d254-4c64-8ba7-6abc04b84d40")
    public static final int CAN_IS_FRAME_11BIT = 0x40000000;

    @objid ("1399ea9b-21a2-4883-90fc-8c8ea8e5ec83")
    public static native void FRCNetworkCommunicationCANSessionMuxSendMessage(int messageID, ByteBuffer data, int periodMs, IntBuffer status);

    @objid ("ebbd6f7b-0696-4499-b946-ca67fc7dc515")
    public static native ByteBuffer FRCNetworkCommunicationCANSessionMuxReceiveMessage(IntBuffer messageID, int messageIDMask, ByteBuffer timeStamp, IntBuffer status);

}
